#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.4 on Mon Sep  9 19:53:12 2013

import wx

# begin wxGlade: extracode
# end wxGlade


class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.logo = wx.StaticBitmap(self, -1, wx.Bitmap("/home/lucas/controle-de-acesso-2/teste/logo.png", wx.BITMAP_TYPE_ANY))
        self.button_administracao = wx.Button(self, -1, u"Administração")
        self.button_horarios = wx.Button(self, -1, u"Horários", style=wx.BU_BOTTOM)
        self.label_titulo1 = wx.StaticText(self, -1, u"Mecajun\nMecatrônica Júnior de Brasília", style=wx.ALIGN_CENTRE)
        self.label_Instrucoes = wx.StaticText(self, -1, u"\nDigite sua matrícula e aperte \"Enter\"\n", style=wx.ALIGN_CENTRE)
        self.label_matricula = wx.StaticText(self, -1, "Matricula:     ")
        self.text_box_matricula = wx.TextCtrl(self, -1, "", style=wx.TE_PROCESS_ENTER)
        self.label_2 = wx.StaticText(self, -1, "Funcionarios esperados:")
        self.list_box_1 = wx.ListBox(self, -1, choices=[])
        self.label_5 = wx.StaticText(self, -1, "label_5")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.adm_Button_Clicked, self.button_administracao)
        self.Bind(wx.EVT_BUTTON, self.horarios_Button_Clicked, self.button_horarios)
        self.Bind(wx.EVT_TEXT_ENTER, self.entrada_Teclado_Matricula, self.text_box_matricula)

        Publisher().subscribe(self.troca_Debug, "evento_mostrar_relogio")
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainFrame.__set_properties
        self.SetTitle("Controle de Acesso")
        self.label_titulo1.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.text_box_matricula.SetMinSize((220, 27))
        self.label_2.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Ubuntu"))
        self.list_box_1.SetMinSize((160, 70))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_22 = wx.BoxSizer(wx.VERTICAL)
        sizer_23 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add(self.logo, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_5.Add(self.button_administracao, 0, wx.EXPAND, 0)
        sizer_5.Add(self.button_horarios, 0, wx.EXPAND | wx.ALIGN_BOTTOM, 0)
        sizer_2.Add(sizer_5, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_2, 4, wx.EXPAND, 0)
        sizer_3.Add(self.label_titulo1, 0, wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_3.Add(self.label_Instrucoes, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_4.Add(self.label_matricula, 0, 0, 0)
        sizer_4.Add(self.text_box_matricula, 0, 0, 0)
        sizer_3.Add(sizer_4, 0, wx.EXPAND, 0)
        sizer_22.Add(self.label_2, 0, 0, 0)
        sizer_23.Add(self.list_box_1, 0, 0, 0)
        sizer_23.Add(self.label_5, 0, wx.ALIGN_BOTTOM, 0)
        sizer_22.Add(sizer_23, 1, wx.EXPAND, 0)
        sizer_3.Add(sizer_22, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_3, 5, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def adm_Button_Clicked(self, event):  # wxGlade: MainFrame.<event_handler>
        print "Event handler `adm_Button_Clicked' not implemented!"
        event.Skip()

    def horarios_Button_Clicked(self, event):  # wxGlade: MainFrame.<event_handler>
        print "Event handler `horarios_Button_Clicked' not implemented!"
        event.Skip()

    def entrada_Teclado_Matricula(self, event):  # wxGlade: MainFrame.<event_handler>
        print "Event handler `entrada_Teclado_Matricula' not implemented!"
        event.Skip()

# end of class MainFrame

class Frame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Frame.__init__
        kwds["style"] = wx.CAPTION | wx.CLOSE_BOX | wx.MINIMIZE_BOX | wx.MAXIMIZE | wx.MAXIMIZE_BOX | wx.SYSTEM_MENU | wx.RESIZE_BORDER | wx.CLIP_CHILDREN
        wx.Frame.__init__(self, *args, **kwds)
        self.notebook_pages = wx.Notebook(self, -1, style=0)
        self.notebook_relatorio = wx.Panel(self.notebook_pages, -1)
        self.label_data_inicial = wx.StaticText(self.notebook_relatorio, -1, "Data Inicial:    ")
        self.datepicker_box_data_inicial = wx.DatePickerCtrl(self.notebook_relatorio, -1)
        self.label_data_final = wx.StaticText(self.notebook_relatorio, -1, "Data Final:      ")
        self.datepicker_box_data_final = wx.DatePickerCtrl(self.notebook_relatorio, -1)
        self.checkbox_pontuais = wx.CheckBox(self.notebook_relatorio, -1, u"Funcionários Pontuais")
        self.checkbox_atrasos = wx.CheckBox(self.notebook_relatorio, -1, u"Funcionários Atrasados")
        self.checkbox_faltas = wx.CheckBox(self.notebook_relatorio, -1, u"Funcionários Faltosos")
        self.button_gerar_relatorio = wx.Button(self.notebook_relatorio, -1, "Gerar")
        self.panel_9 = wx.Panel(self.notebook_pages, -1)
        self.label_22 = wx.StaticText(self.panel_9, -1, u"Tolerância Entrada:")
        self.spin_ctrl_9 = wx.SpinCtrl(self.panel_9, -1, "", min=0, max=100)
        self.label_26 = wx.StaticText(self.panel_9, -1, "        antes e")
        self.spin_ctrl_11 = wx.SpinCtrl(self.panel_9, -1, "", min=0, max=100)
        self.label_28 = wx.StaticText(self.panel_9, -1, "     depois")
        self.panel_10 = wx.Panel(self.panel_9, -1)
        self.label_23 = wx.StaticText(self.panel_9, -1, u"Tolerância Saída:")
        self.spin_ctrl_10 = wx.SpinCtrl(self.panel_9, -1, "", min=0, max=100)
        self.label_27 = wx.StaticText(self.panel_9, -1, "        depois")
        self.panel_11 = wx.Panel(self.panel_9, -1)
        self.panel_14 = wx.Panel(self.panel_9, -1)
        self.label_24 = wx.StaticText(self.panel_9, -1, u"Pontos Simultâneos:")
        self.spin_ctrl_12 = wx.SpinCtrl(self.panel_9, -1, "", min=0, max=100)
        self.panel_12 = wx.Panel(self.panel_9, -1)
        self.panel_15 = wx.Panel(self.panel_9, -1)
        self.label_25 = wx.StaticText(self.panel_9, -1, u"Considerar atraso após")
        self.spin_ctrl_13 = wx.SpinCtrl(self.panel_9, -1, "", min=0, max=100)
        self.panel_13 = wx.Panel(self.panel_9, -1)
        self.panel_16 = wx.Panel(self.panel_9, -1)
        self.button_1 = wx.Button(self.panel_9, -1, "Alterar senha do Administrador")
        self.panel_17 = wx.Panel(self.panel_9, -1)
        self.notebook_1_funcionarios = wx.Panel(self.notebook_pages, -1)
        self.label_funcionarios_lista = wx.StaticText(self.notebook_1_funcionarios, -1, "\nFuncionarios cadastrados\n", style=wx.ALIGN_CENTRE)
        self.list_funcionarios = wx.ListBox(self.notebook_1_funcionarios, -1, choices=[], style=wx.LB_SINGLE)
        self.button_remover_funcionario = wx.Button(self.notebook_1_funcionarios, -1, "Remover")
        self.label_Funcionarios_add_desc = wx.StaticText(self.notebook_1_funcionarios, -1, u"\nAdicione um novo funcionário\n", style=wx.ALIGN_CENTRE)
        self.label_funcionarios_add = wx.StaticText(self.notebook_1_funcionarios, -1, "Nome")
        self.text_box_nome_adicionar_func = wx.TextCtrl(self.notebook_1_funcionarios, -1, "")
        self.label_informacao_func = wx.StaticText(self.notebook_1_funcionarios, -1, u"Informações detalhadas do funcionario")
        self.label_matricula_adm = wx.StaticText(self.notebook_1_funcionarios, -1, "Matricula")
        self.text_box_matricula = wx.TextCtrl(self.notebook_1_funcionarios, -1, "")
        self.label_rfid_adm = wx.StaticText(self.notebook_1_funcionarios, -1, "RFID")
        self.button_obter_rfid = wx.Button(self.notebook_1_funcionarios, -1, "Obter RFID")
        self.label_data_adm = wx.StaticText(self.notebook_1_funcionarios, -1, "Data")
        self.combo_box_datas_adm = wx.ComboBox(self.notebook_1_funcionarios, -1, choices=["Segunda", u"Terça", "Quarta", "Quinta", "Sexta", "Sabado", "Domingo"], style=wx.CB_DROPDOWN)
        self.label_hora = wx.StaticText(self.notebook_1_funcionarios, -1, "Hora")
        self.label_hora_inicial = wx.StaticText(self.notebook_1_funcionarios, -1, "Inicio")
        self.text_box_hora_inicial = wx.TextCtrl(self.notebook_1_funcionarios, -1, "")
        self.label_hora_final = wx.StaticText(self.notebook_1_funcionarios, -1, "   Fim")
        self.text_box_hora_final = wx.TextCtrl(self.notebook_1_funcionarios, -1, "")
        self.list_box_horarios = wx.ListBox(self.notebook_1_funcionarios, -1, choices=[])
        self.button_adicionar_horario = wx.Button(self.notebook_1_funcionarios, -1, "Adicionar")
        self.button_remover_horario = wx.Button(self.notebook_1_funcionarios, -1, "Remover")
        self.button_salvar_alteracoes = wx.Button(self.notebook_1_funcionarios, -1, u"Salvar alterações", style=wx.BU_RIGHT)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.button_Gerar_Relatorio, self.button_gerar_relatorio)
        self.Bind(wx.EVT_LISTBOX, self.detalhar_funcionario, self.list_funcionarios)
        self.Bind(wx.EVT_BUTTON, self.button_Remover_Funcionario, self.button_remover_funcionario)
        self.Bind(wx.EVT_BUTTON, self.button_Obter_Rfid, self.button_obter_rfid)
        self.Bind(wx.EVT_BUTTON, self.button_Adicionar_Hora, self.button_adicionar_horario)
        self.Bind(wx.EVT_BUTTON, self.button_Remover_Hora, self.button_remover_horario)
        self.Bind(wx.EVT_BUTTON, self.button_Salvar_Alteracoes, self.button_salvar_alteracoes)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Frame.__set_properties
        self.SetTitle("Menu Administrativo")
        self.datepicker_box_data_inicial.SetMinSize((300, 27))
        self.datepicker_box_data_final.SetMinSize((300, 27))
        self.checkbox_pontuais.SetValue(1)
        self.checkbox_atrasos.SetValue(1)
        self.checkbox_faltas.SetValue(1)
        self.list_funcionarios.SetMinSize((220, 300))
        self.text_box_nome_adicionar_func.SetMinSize((200, 27))
        self.combo_box_datas_adm.SetSelection(-1)
        self.list_box_horarios.SetMinSize((400, 100))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Frame.__do_layout
        sizer_7 = wx.BoxSizer(wx.VERTICAL)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_15 = wx.BoxSizer(wx.VERTICAL)
        sizer_17 = wx.BoxSizer(wx.VERTICAL)
        sizer_18 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_16 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_1 = wx.GridSizer(5, 2, 0, 0)
        sizer_19 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10 = wx.BoxSizer(wx.VERTICAL)
        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_32 = wx.BoxSizer(wx.VERTICAL)
        sizer_36 = wx.BoxSizer(wx.VERTICAL)
        sizer_37 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_2 = wx.GridSizer(4, 4, 0, 0)
        sizer_34 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_35 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_33 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9 = wx.BoxSizer(wx.VERTICAL)
        sizer_14 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_13 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_12 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9.Add((20, 20), 0, 0, 0)
        sizer_12.Add(self.label_data_inicial, 0, 0, 0)
        sizer_12.Add(self.datepicker_box_data_inicial, 0, 0, 0)
        sizer_9.Add(sizer_12, 1, wx.EXPAND, 0)
        sizer_9.Add((20, 20), 0, 0, 0)
        sizer_13.Add(self.label_data_final, 0, 0, 0)
        sizer_13.Add(self.datepicker_box_data_final, 0, 0, 0)
        sizer_9.Add(sizer_13, 1, wx.EXPAND, 0)
        sizer_9.Add((20, 20), 0, 0, 0)
        sizer_14.Add(self.checkbox_pontuais, 0, 0, 0)
        sizer_14.Add(self.checkbox_atrasos, 0, 0, 0)
        sizer_14.Add(self.checkbox_faltas, 0, 0, 0)
        sizer_9.Add(sizer_14, 1, wx.EXPAND, 0)
        sizer_9.Add(self.button_gerar_relatorio, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_9.Add((20, 20), 0, 0, 0)
        self.notebook_relatorio.SetSizer(sizer_9)
        sizer_32.Add((20, 20), 0, 0, 0)
        grid_sizer_2.Add(self.label_22, 0, 0, 0)
        sizer_33.Add(self.spin_ctrl_9, 0, 0, 0)
        sizer_33.Add(self.label_26, 0, 0, 0)
        grid_sizer_2.Add(sizer_33, 1, wx.EXPAND, 0)
        sizer_35.Add(self.spin_ctrl_11, 0, 0, 0)
        sizer_35.Add(self.label_28, 0, 0, 0)
        grid_sizer_2.Add(sizer_35, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.panel_10, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.label_23, 0, 0, 0)
        sizer_34.Add(self.spin_ctrl_10, 0, 0, 0)
        sizer_34.Add(self.label_27, 0, 0, 0)
        grid_sizer_2.Add(sizer_34, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.panel_11, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.panel_14, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.label_24, 0, 0, 0)
        grid_sizer_2.Add(self.spin_ctrl_12, 0, 0, 0)
        grid_sizer_2.Add(self.panel_12, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.panel_15, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.label_25, 0, 0, 0)
        grid_sizer_2.Add(self.spin_ctrl_13, 0, 0, 0)
        grid_sizer_2.Add(self.panel_13, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.panel_16, 1, wx.EXPAND, 0)
        sizer_32.Add(grid_sizer_2, 0, wx.EXPAND, 0)
        sizer_36.Add((20, 20), 0, 0, 0)
        sizer_37.Add(self.button_1, 0, 0, 0)
        sizer_37.Add(self.panel_17, 1, 0, 0)
        sizer_36.Add(sizer_37, 1, wx.EXPAND, 0)
        sizer_32.Add(sizer_36, 1, wx.EXPAND, 0)
        self.panel_9.SetSizer(sizer_32)
        sizer_10.Add(self.label_funcionarios_lista, 0, wx.EXPAND, 0)
        sizer_10.Add(self.list_funcionarios, 0, wx.EXPAND, 0)
        sizer_10.Add(self.button_remover_funcionario, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_10.Add(self.label_Funcionarios_add_desc, 0, wx.EXPAND, 0)
        sizer_11.Add(self.label_funcionarios_add, 0, 0, 0)
        sizer_11.Add(self.text_box_nome_adicionar_func, 0, wx.EXPAND, 0)
        sizer_10.Add(sizer_11, 0, wx.EXPAND, 0)
        sizer_8.Add(sizer_10, 0, 0, 0)
        sizer_6.Add((20, 20), 0, 0, 0)
        grid_sizer_1.Add(self.label_informacao_func, 0, 0, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        grid_sizer_1.Add(self.label_matricula_adm, 0, 0, 0)
        grid_sizer_1.Add(self.text_box_matricula, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.label_rfid_adm, 0, 0, 0)
        grid_sizer_1.Add(self.button_obter_rfid, 0, 0, 0)
        grid_sizer_1.Add(self.label_data_adm, 0, 0, 0)
        grid_sizer_1.Add(self.combo_box_datas_adm, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.label_hora, 0, 0, 0)
        sizer_19.Add(self.label_hora_inicial, 0, 0, 0)
        sizer_19.Add(self.text_box_hora_inicial, 0, 0, 0)
        sizer_19.Add(self.label_hora_final, 0, 0, 0)
        sizer_19.Add(self.text_box_hora_final, 0, 0, 0)
        grid_sizer_1.Add(sizer_19, 1, wx.EXPAND, 0)
        sizer_16.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        sizer_15.Add(sizer_16, 1, wx.EXPAND, 0)
        sizer_17.Add(self.list_box_horarios, 0, wx.EXPAND, 0)
        sizer_18.Add(self.button_adicionar_horario, 0, 0, 0)
        sizer_18.Add(self.button_remover_horario, 0, 0, 0)
        sizer_17.Add(sizer_18, 1, wx.EXPAND, 0)
        sizer_15.Add(sizer_17, 1, wx.EXPAND, 0)
        sizer_15.Add(self.button_salvar_alteracoes, 0, 0, 0)
        sizer_6.Add(sizer_15, 1, wx.EXPAND, 0)
        sizer_6.Add((20, 20), 0, 0, 0)
        sizer_8.Add(sizer_6, 1, wx.EXPAND, 0)
        self.notebook_1_funcionarios.SetSizer(sizer_8)
        self.notebook_pages.AddPage(self.notebook_relatorio, "Relatorio")
        self.notebook_pages.AddPage(self.panel_9, u"Configurações")
        self.notebook_pages.AddPage(self.notebook_1_funcionarios, "Funcionarios")
        sizer_7.Add(self.notebook_pages, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_7)
        sizer_7.Fit(self)
        self.Layout()
        # end wxGlade

    def button_Gerar_Relatorio(self, event):  # wxGlade: Frame.<event_handler>
        print "Event handler `button_Gerar_Relatorio' not implemented!"
        event.Skip()

    def detalhar_funcionario(self, event):  # wxGlade: Frame.<event_handler>
        print "Event handler `detalhar_funcionario' not implemented!"
        event.Skip()

    def button_Remover_Funcionario(self, event):  # wxGlade: Frame.<event_handler>
        print "Event handler `button_Remover_Funcionario' not implemented!"
        event.Skip()

    def button_Obter_Rfid(self, event):  # wxGlade: Frame.<event_handler>
        print "Event handler `button_Obter_Rfid' not implemented!"
        event.Skip()

    def button_Adicionar_Hora(self, event):  # wxGlade: Frame.<event_handler>
        print "Event handler `button_Adicionar_Hora' not implemented!"
        event.Skip()

    def button_Remover_Hora(self, event):  # wxGlade: Frame.<event_handler>
        print "Event handler `button_Remover_Hora' not implemented!"
        event.Skip()

    def button_Salvar_Alteracoes(self, event):  # wxGlade: Frame.<event_handler>
        print "Event handler `button_Salvar_Alteracoes' not implemented!"
        event.Skip()

# end of class Frame
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    janela_principal = MainFrame(None, -1, "")
    app.SetTopWindow(janela_principal)
    janela_principal.Show()
    app.MainLoop()
