.TH "auxiliares.py" 3 "Terça, 24 de Dezembro de 2013" "Version 2" "Controle de Acesso" \" -*- nroff -*-
.ad l
.nh
.SH NAME
auxiliares.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Componentes"

.in +1c
.ti -1c
.RI "class \fBauxiliares\&.CSV\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBauxiliares\fP"
.br
.in -1c
.SS "Funções"

.in +1c
.ti -1c
.RI "def \fBauxiliares\&.criptografar_Senha\fP"
.br
.ti -1c
.RI "def \fBauxiliares\&.dia_Semana_Int2str\fP"
.br
.ti -1c
.RI "def \fBauxiliares\&.set_proc_name\fP"
.br
.RI "\fIAltera o nome do processo  newname Novo nome do processo\&. \fP"
.ti -1c
.RI "def \fBauxiliares\&.get_Week_Day\fP"
.br
.ti -1c
.RI "def \fBauxiliares\&.string_2_Timedelta\fP"
.br
.ti -1c
.RI "def \fBauxiliares\&.string_2_Time\fP"
.br
.ti -1c
.RI "def \fBauxiliares\&.data_Atual\fP"
.br
.in -1c
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Controle de Acesso a partir do código fonte\&.
