.TH "cda_removerfuncionario.Ui_Remover_Funcionarios_Window" 3 "Terça, 24 de Dezembro de 2013" "Version 2" "Controle de Acesso" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cda_removerfuncionario.Ui_Remover_Funcionarios_Window \- 
.SH SYNOPSIS
.br
.PP
.PP
Herdado por \fBview\&.Remover_Funcionarios_Window\fP\&.
.SS "Membros públicos"

.in +1c
.ti -1c
.RI "def \fBsetupUi\fP"
.br
.ti -1c
.RI "def \fBretranslateUi\fP"
.br
.in -1c
.SS "Atributos Públicos"

.in +1c
.ti -1c
.RI "\fBcentralwidget\fP"
.br
.ti -1c
.RI "\fBlayoutWidget\fP"
.br
.ti -1c
.RI "\fBverticalLayout_2\fP"
.br
.ti -1c
.RI "\fBlabel\fP"
.br
.ti -1c
.RI "\fBlistView_funcionarios\fP"
.br
.ti -1c
.RI "\fBpushButton_remover_funcionario\fP"
.br
.ti -1c
.RI "\fBmenubar\fP"
.br
.in -1c
.SH "Descrição detalhada"
.PP 
Definido na linha 12 do ficheiro cda_removerfuncionario\&.py\&.
.SH "Documentação dos métodos"
.PP 
.SS "def \fBcda_removerfuncionario\&.Ui_Remover_Funcionarios_Window\&.retranslateUi\fP (self, Remover_Funcionarios_Window)"
.PP
Definido na linha 43 do ficheiro cda_removerfuncionario\&.py\&.
.PP
.nf
43 
44     def retranslateUi(self, Remover_Funcionarios_Window):
45         Remover_Funcionarios_Window\&.setWindowTitle(QtGui\&.QApplication\&.translate('Remover_Funcionarios_Window', 'Remover Funcionarios', None, QtGui\&.QApplication\&.UnicodeUTF8))
46         self\&.label\&.setText(QtGui\&.QApplication\&.translate('Remover_Funcionarios_Window', 'Funcionarios Cadastrados', None, QtGui\&.QApplication\&.UnicodeUTF8))
47         self\&.pushButton_remover_funcionario\&.setText(QtGui\&.QApplication\&.translate('Remover_Funcionarios_Window', 'Remover Funcionario', None, QtGui\&.QApplication\&.UnicodeUTF8))
48 
.fi
.SS "def \fBcda_removerfuncionario\&.Ui_Remover_Funcionarios_Window\&.setupUi\fP (self, Remover_Funcionarios_Window)"
.PP
Definido na linha 13 do ficheiro cda_removerfuncionario\&.py\&.
.PP
.nf
13 
14     def setupUi(self, Remover_Funcionarios_Window):
15         Remover_Funcionarios_Window\&.setObjectName('Remover_Funcionarios_Window')
16         Remover_Funcionarios_Window\&.resize(277, 503)
17         Remover_Funcionarios_Window\&.setLocale(QtCore\&.QLocale(QtCore\&.QLocale\&.Portuguese, QtCore\&.QLocale\&.Brazil))
18         self\&.centralwidget = QtGui\&.QWidget(Remover_Funcionarios_Window)
19         self\&.centralwidget\&.setObjectName('centralwidget')
20         self\&.layoutWidget = QtGui\&.QWidget(self\&.centralwidget)
21         self\&.layoutWidget\&.setGeometry(QtCore\&.QRect(10, 10, 258, 421))
22         self\&.layoutWidget\&.setObjectName('layoutWidget')
23         self\&.verticalLayout_2 = QtGui\&.QVBoxLayout(self\&.layoutWidget)
24         self\&.verticalLayout_2\&.setContentsMargins(0, 0, 0, 0)
25         self\&.verticalLayout_2\&.setObjectName('verticalLayout_2')
26         self\&.label = QtGui\&.QLabel(self\&.layoutWidget)
27         self\&.label\&.setObjectName('label')
28         self\&.verticalLayout_2\&.addWidget(self\&.label)
29         self\&.listView_funcionarios = QtGui\&.QListView(self\&.layoutWidget)
30         self\&.listView_funcionarios\&.setObjectName('listView_funcionarios')
31         self\&.verticalLayout_2\&.addWidget(self\&.listView_funcionarios)
32         self\&.pushButton_remover_funcionario = QtGui\&.QPushButton(self\&.centralwidget)
33         self\&.pushButton_remover_funcionario\&.setGeometry(QtCore\&.QRect(50, 440, 180, 27))
34         self\&.pushButton_remover_funcionario\&.setObjectName('pushButton_remover_funcionario')
35         Remover_Funcionarios_Window\&.setCentralWidget(self\&.centralwidget)
36         self\&.menubar = QtGui\&.QMenuBar(Remover_Funcionarios_Window)
37         self\&.menubar\&.setGeometry(QtCore\&.QRect(0, 0, 277, 25))
38         self\&.menubar\&.setObjectName('menubar')
39         Remover_Funcionarios_Window\&.setMenuBar(self\&.menubar)
40 
41         self\&.retranslateUi(Remover_Funcionarios_Window)
42         QtCore\&.QMetaObject\&.connectSlotsByName(Remover_Funcionarios_Window)

.fi
.SH "Documentação dos dados membro"
.PP 
.SS "\fBcda_removerfuncionario\&.Ui_Remover_Funcionarios_Window::centralwidget\fP"
.PP
Definido na linha 13 do ficheiro cda_removerfuncionario\&.py\&.
.SS "\fBcda_removerfuncionario\&.Ui_Remover_Funcionarios_Window::label\fP"
.PP
Definido na linha 13 do ficheiro cda_removerfuncionario\&.py\&.
.SS "\fBcda_removerfuncionario\&.Ui_Remover_Funcionarios_Window::layoutWidget\fP"
.PP
Definido na linha 13 do ficheiro cda_removerfuncionario\&.py\&.
.SS "\fBcda_removerfuncionario\&.Ui_Remover_Funcionarios_Window::listView_funcionarios\fP"
.PP
Definido na linha 13 do ficheiro cda_removerfuncionario\&.py\&.
.SS "\fBcda_removerfuncionario\&.Ui_Remover_Funcionarios_Window::menubar\fP"
.PP
Definido na linha 13 do ficheiro cda_removerfuncionario\&.py\&.
.SS "\fBcda_removerfuncionario\&.Ui_Remover_Funcionarios_Window::pushButton_remover_funcionario\fP"
.PP
Definido na linha 13 do ficheiro cda_removerfuncionario\&.py\&.
.SS "\fBcda_removerfuncionario\&.Ui_Remover_Funcionarios_Window::verticalLayout_2\fP"
.PP
Definido na linha 13 do ficheiro cda_removerfuncionario\&.py\&.

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Controle de Acesso a partir do código fonte\&.
