.TH "instalar.py" 3 "Terça, 24 de Dezembro de 2013" "Version 2" "Controle de Acesso" \" -*- nroff -*-
.ad l
.nh
.SH NAME
instalar.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Componentes"

.in +1c
.ti -1c
.RI "class \fBinstalar\&.Connect_MySQL\fP"
.br
.RI "\fIClasse de conexão e acesso ao banco de dados\&. \fP"
.ti -1c
.RI "class \fBinstalar\&.Instalar\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBinstalar\fP"
.br
.in -1c
.SS "Variáveis"

.in +1c
.ti -1c
.RI "tuple \fBinstalar\&.db\fP = Connect_MySQL('localhost','root','42')"
.br
.ti -1c
.RI "tuple \fBinstalar\&.ins\fP = Instalar(db)"
.br
.in -1c
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Controle de Acesso a partir do código fonte\&.
