.TH "main.py" 3 "Terça, 24 de Dezembro de 2013" "Version 2" "Controle de Acesso" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmain\fP"
.br
.in -1c
.SS "Variáveis"

.in +1c
.ti -1c
.RI "dictionary \fBmain\&.db_dados\fP = {'host':'localhost','user':'root','passwd':'42'}"
.br
.ti -1c
.RI "tuple \fBmain\&.app\fP = QApplication(sys\&.argv)"
.br
.ti -1c
.RI "tuple \fBmain\&.ex\fP = \fBview\&.Controle_De_Acesso_Window\fP(None,db_dados)"
.br
.in -1c
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Controle de Acesso a partir do código fonte\&.
