# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tolerancias.ui'
#
# Created: Mon Jul  7 12:17:58 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Tolerancias_Window(object):
    def setupUi(self, Tolerancias_Window):
        Tolerancias_Window.setObjectName("Tolerancias_Window")
        Tolerancias_Window.resize(392, 259)
        Tolerancias_Window.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.centralwidget = QtGui.QWidget(Tolerancias_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 361, 201))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.timeEdit_entrada_antes = QtGui.QTimeEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeEdit_entrada_antes.sizePolicy().hasHeightForWidth())
        self.timeEdit_entrada_antes.setSizePolicy(sizePolicy)
        self.timeEdit_entrada_antes.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.timeEdit_entrada_antes.setObjectName("timeEdit_entrada_antes")
        self.horizontalLayout.addWidget(self.timeEdit_entrada_antes)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.timeEdit_entrada_depois = QtGui.QTimeEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeEdit_entrada_depois.sizePolicy().hasHeightForWidth())
        self.timeEdit_entrada_depois.setSizePolicy(sizePolicy)
        self.timeEdit_entrada_depois.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.timeEdit_entrada_depois.setObjectName("timeEdit_entrada_depois")
        self.horizontalLayout.addWidget(self.timeEdit_entrada_depois)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.timeEdit_saida_antes = QtGui.QTimeEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeEdit_saida_antes.sizePolicy().hasHeightForWidth())
        self.timeEdit_saida_antes.setSizePolicy(sizePolicy)
        self.timeEdit_saida_antes.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.timeEdit_saida_antes.setObjectName("timeEdit_saida_antes")
        self.horizontalLayout_2.addWidget(self.timeEdit_saida_antes)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.timeEdit_saida_depois = QtGui.QTimeEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeEdit_saida_depois.sizePolicy().hasHeightForWidth())
        self.timeEdit_saida_depois.setSizePolicy(sizePolicy)
        self.timeEdit_saida_depois.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.timeEdit_saida_depois.setObjectName("timeEdit_saida_depois")
        self.horizontalLayout_2.addWidget(self.timeEdit_saida_depois)
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.timeEdit_atraso = QtGui.QTimeEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeEdit_atraso.sizePolicy().hasHeightForWidth())
        self.timeEdit_atraso.setSizePolicy(sizePolicy)
        self.timeEdit_atraso.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.timeEdit_atraso.setObjectName("timeEdit_atraso")
        self.horizontalLayout_3.addWidget(self.timeEdit_atraso)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButton_salvar = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_salvar.sizePolicy().hasHeightForWidth())
        self.pushButton_salvar.setSizePolicy(sizePolicy)
        self.pushButton_salvar.setObjectName("pushButton_salvar")
        self.horizontalLayout_3.addWidget(self.pushButton_salvar)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        Tolerancias_Window.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Tolerancias_Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 392, 25))
        self.menubar.setObjectName("menubar")
        Tolerancias_Window.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Tolerancias_Window)
        self.statusbar.setObjectName("statusbar")
        Tolerancias_Window.setStatusBar(self.statusbar)

        self.retranslateUi(Tolerancias_Window)
        QtCore.QMetaObject.connectSlotsByName(Tolerancias_Window)

    def retranslateUi(self, Tolerancias_Window):
        Tolerancias_Window.setWindowTitle(QtGui.QApplication.translate("Tolerancias_Window", "Tolerancias", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Tolerancias_Window", "Tolerancia Entrada", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Tolerancias_Window", "Antes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Tolerancias_Window", "Depois", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Tolerancias_Window", "Toletancia Saida", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Tolerancias_Window", "Antes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Tolerancias_Window", "Depois", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Tolerancias_Window", "Considerar atraso", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_salvar.setText(QtGui.QApplication.translate("Tolerancias_Window", "Salvar", None, QtGui.QApplication.UnicodeUTF8))

