.TH "auxiliares.CSV" 3 "Terça, 24 de Dezembro de 2013" "Version 2" "Controle de Acesso" \" -*- nroff -*-
.ad l
.nh
.SH NAME
auxiliares.CSV \- 
.SH SYNOPSIS
.br
.PP
.SS "Membros públicos"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBwriterow\fP"
.br
.ti -1c
.RI "def \fBfinaliza\fP"
.br
.in -1c
.SS "Atributos Públicos"

.in +1c
.ti -1c
.RI "\fBfile\fP"
.br
.ti -1c
.RI "\fBseparador\fP"
.br
.in -1c
.SH "Descrição detalhada"
.PP 
.PP
.nf
docstring for CSV.fi
.PP
 
.PP
Definido na linha 7 do ficheiro auxiliares\&.py\&.
.SH "Documentação dos Construtores & Destrutor"
.PP 
.SS "def \fBauxiliares\&.CSV\&.__init__\fP (self, file_name, mode = \fC'w+'\fP, separador = \fC'\fP)"
.PP
Definido na linha 9 do ficheiro auxiliares\&.py\&.
.PP
.nf
9 
10     def __init__(self, file_name, mode='w+', separador=','):
11         try:
12             self\&.file=open(file_name,mode)
13         except Exception:
14             full_path = os\&.path\&.realpath(__file__)
15             directory=os\&.path\&.dirname(full_path)
16             os\&.makedirs(directory+'/relatorios')
17         finally:
18             self\&.file=open(file_name,mode)
        self\&.separador=separador
.fi
.SH "Documentação dos métodos"
.PP 
.SS "def \fBauxiliares\&.CSV\&.finaliza\fP (self)"
.PP
Definido na linha 32 do ficheiro auxiliares\&.py\&.
.PP
.nf
32 
33     def finaliza(self):
34         self\&.file\&.close()

.fi
.SS "def \fBauxiliares\&.CSV\&.writerow\fP (self, linha)"
.PP
Definido na linha 19 do ficheiro auxiliares\&.py\&.
.PP
.nf
19 
20     def writerow(self,linha):
21         temp_str=u''
22         for elem in linha:
23             try:
24                 if not (isinstance(elem, str) or isinstance(elem, unicode)):
25                     temp_str=temp_str+str(elem)+self\&.separador
26                 else:
27                     temp_str=temp_str+elem+self\&.separador
28             except UnicodeDecodeError:
29                 print elem
30         temp_str=temp_str[:-len(self\&.separador)]+'\n'
31         self\&.file\&.write(temp_str\&.encode('utf8'))
    
.fi
.SH "Documentação dos dados membro"
.PP 
.SS "\fBauxiliares\&.CSV::file\fP"
.PP
Definido na linha 9 do ficheiro auxiliares\&.py\&.
.SS "\fBauxiliares\&.CSV::separador\fP"
.PP
Definido na linha 9 do ficheiro auxiliares\&.py\&.
.PP
Referenciado por auxiliares\&.CSV\&.writerow()\&.

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Controle de Acesso a partir do código fonte\&.
