.TH "cda_tolerancias.Ui_Tolerancias_Window" 3 "Terça, 24 de Dezembro de 2013" "Version 2" "Controle de Acesso" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cda_tolerancias.Ui_Tolerancias_Window \- 
.SH SYNOPSIS
.br
.PP
.PP
Herdado por \fBview\&.Tolerancias_Window\fP\&.
.SS "Membros públicos"

.in +1c
.ti -1c
.RI "def \fBsetupUi\fP"
.br
.ti -1c
.RI "def \fBretranslateUi\fP"
.br
.in -1c
.SS "Atributos Públicos"

.in +1c
.ti -1c
.RI "\fBcentralwidget\fP"
.br
.ti -1c
.RI "\fBlayoutWidget\fP"
.br
.ti -1c
.RI "\fBverticalLayout\fP"
.br
.ti -1c
.RI "\fBlabel\fP"
.br
.ti -1c
.RI "\fBhorizontalLayout\fP"
.br
.ti -1c
.RI "\fBtimeEdit_entrada_antes\fP"
.br
.ti -1c
.RI "\fBlabel_4\fP"
.br
.ti -1c
.RI "\fBtimeEdit_entrada_depois\fP"
.br
.ti -1c
.RI "\fBlabel_5\fP"
.br
.ti -1c
.RI "\fBlabel_2\fP"
.br
.ti -1c
.RI "\fBhorizontalLayout_2\fP"
.br
.ti -1c
.RI "\fBtimeEdit_saida_antes\fP"
.br
.ti -1c
.RI "\fBlabel_6\fP"
.br
.ti -1c
.RI "\fBtimeEdit_saida_depois\fP"
.br
.ti -1c
.RI "\fBlabel_7\fP"
.br
.ti -1c
.RI "\fBlabel_3\fP"
.br
.ti -1c
.RI "\fBhorizontalLayout_3\fP"
.br
.ti -1c
.RI "\fBtimeEdit_atraso\fP"
.br
.ti -1c
.RI "\fBpushButton_salvar\fP"
.br
.ti -1c
.RI "\fBmenubar\fP"
.br
.ti -1c
.RI "\fBstatusbar\fP"
.br
.in -1c
.SH "Descrição detalhada"
.PP 
Definido na linha 12 do ficheiro cda_tolerancias\&.py\&.
.SH "Documentação dos métodos"
.PP 
.SS "def \fBcda_tolerancias\&.Ui_Tolerancias_Window\&.retranslateUi\fP (self, Tolerancias_Window)"
.PP
Definido na linha 124 do ficheiro cda_tolerancias\&.py\&.
.PP
.nf
124 
125     def retranslateUi(self, Tolerancias_Window):
126         Tolerancias_Window\&.setWindowTitle(QtGui\&.QApplication\&.translate('Tolerancias_Window', 'Tolerancias', None, QtGui\&.QApplication\&.UnicodeUTF8))
127         self\&.label\&.setText(QtGui\&.QApplication\&.translate('Tolerancias_Window', 'Tolerancia Entrada', None, QtGui\&.QApplication\&.UnicodeUTF8))
128         self\&.label_4\&.setText(QtGui\&.QApplication\&.translate('Tolerancias_Window', 'Antes', None, QtGui\&.QApplication\&.UnicodeUTF8))
129         self\&.label_5\&.setText(QtGui\&.QApplication\&.translate('Tolerancias_Window', 'Depois', None, QtGui\&.QApplication\&.UnicodeUTF8))
130         self\&.label_2\&.setText(QtGui\&.QApplication\&.translate('Tolerancias_Window', 'Toletancia Saida', None, QtGui\&.QApplication\&.UnicodeUTF8))
131         self\&.label_6\&.setText(QtGui\&.QApplication\&.translate('Tolerancias_Window', 'Antes', None, QtGui\&.QApplication\&.UnicodeUTF8))
132         self\&.label_7\&.setText(QtGui\&.QApplication\&.translate('Tolerancias_Window', 'Depois', None, QtGui\&.QApplication\&.UnicodeUTF8))
133         self\&.label_3\&.setText(QtGui\&.QApplication\&.translate('Tolerancias_Window', 'Considerar atraso', None, QtGui\&.QApplication\&.UnicodeUTF8))
134         self\&.pushButton_salvar\&.setText(QtGui\&.QApplication\&.translate('Tolerancias_Window', 'Salvar', None, QtGui\&.QApplication\&.UnicodeUTF8))
135 
.fi
.SS "def \fBcda_tolerancias\&.Ui_Tolerancias_Window\&.setupUi\fP (self, Tolerancias_Window)"
.PP
Definido na linha 13 do ficheiro cda_tolerancias\&.py\&.
.PP
.nf
13 
14     def setupUi(self, Tolerancias_Window):
15         Tolerancias_Window\&.setObjectName('Tolerancias_Window')
16         Tolerancias_Window\&.resize(392, 259)
17         Tolerancias_Window\&.setLocale(QtCore\&.QLocale(QtCore\&.QLocale\&.Portuguese, QtCore\&.QLocale\&.Brazil))
18         self\&.centralwidget = QtGui\&.QWidget(Tolerancias_Window)
19         self\&.centralwidget\&.setObjectName('centralwidget')
20         self\&.layoutWidget = QtGui\&.QWidget(self\&.centralwidget)
21         self\&.layoutWidget\&.setGeometry(QtCore\&.QRect(20, 10, 361, 201))
22         self\&.layoutWidget\&.setObjectName('layoutWidget')
23         self\&.verticalLayout = QtGui\&.QVBoxLayout(self\&.layoutWidget)
24         self\&.verticalLayout\&.setContentsMargins(0, 0, 0, 0)
25         self\&.verticalLayout\&.setObjectName('verticalLayout')
26         self\&.label = QtGui\&.QLabel(self\&.layoutWidget)
27         self\&.label\&.setObjectName('label')
28         self\&.verticalLayout\&.addWidget(self\&.label)
29         self\&.horizontalLayout = QtGui\&.QHBoxLayout()
30         self\&.horizontalLayout\&.setObjectName('horizontalLayout')
31         self\&.timeEdit_entrada_antes = QtGui\&.QTimeEdit(self\&.layoutWidget)
32         sizePolicy = QtGui\&.QSizePolicy(QtGui\&.QSizePolicy\&.Fixed, QtGui\&.QSizePolicy\&.Fixed)
33         sizePolicy\&.setHorizontalStretch(0)
34         sizePolicy\&.setVerticalStretch(0)
35         sizePolicy\&.setHeightForWidth(self\&.timeEdit_entrada_antes\&.sizePolicy()\&.hasHeightForWidth())
36         self\&.timeEdit_entrada_antes\&.setSizePolicy(sizePolicy)
37         self\&.timeEdit_entrada_antes\&.setLocale(QtCore\&.QLocale(QtCore\&.QLocale\&.Portuguese, QtCore\&.QLocale\&.Brazil))
38         self\&.timeEdit_entrada_antes\&.setObjectName('timeEdit_entrada_antes')
39         self\&.horizontalLayout\&.addWidget(self\&.timeEdit_entrada_antes)
40         self\&.label_4 = QtGui\&.QLabel(self\&.layoutWidget)
41         self\&.label_4\&.setObjectName('label_4')
42         self\&.horizontalLayout\&.addWidget(self\&.label_4)
43         self\&.timeEdit_entrada_depois = QtGui\&.QTimeEdit(self\&.layoutWidget)
44         sizePolicy = QtGui\&.QSizePolicy(QtGui\&.QSizePolicy\&.Fixed, QtGui\&.QSizePolicy\&.Fixed)
45         sizePolicy\&.setHorizontalStretch(0)
46         sizePolicy\&.setVerticalStretch(0)
47         sizePolicy\&.setHeightForWidth(self\&.timeEdit_entrada_depois\&.sizePolicy()\&.hasHeightForWidth())
48         self\&.timeEdit_entrada_depois\&.setSizePolicy(sizePolicy)
49         self\&.timeEdit_entrada_depois\&.setLocale(QtCore\&.QLocale(QtCore\&.QLocale\&.Portuguese, QtCore\&.QLocale\&.Brazil))
50         self\&.timeEdit_entrada_depois\&.setObjectName('timeEdit_entrada_depois')
51         self\&.horizontalLayout\&.addWidget(self\&.timeEdit_entrada_depois)
52         self\&.label_5 = QtGui\&.QLabel(self\&.layoutWidget)
53         self\&.label_5\&.setObjectName('label_5')
54         self\&.horizontalLayout\&.addWidget(self\&.label_5)
55         self\&.verticalLayout\&.addLayout(self\&.horizontalLayout)
56         self\&.label_2 = QtGui\&.QLabel(self\&.layoutWidget)
57         self\&.label_2\&.setObjectName('label_2')
58         self\&.verticalLayout\&.addWidget(self\&.label_2)
59         self\&.horizontalLayout_2 = QtGui\&.QHBoxLayout()
60         self\&.horizontalLayout_2\&.setObjectName('horizontalLayout_2')
61         self\&.timeEdit_saida_antes = QtGui\&.QTimeEdit(self\&.layoutWidget)
62         sizePolicy = QtGui\&.QSizePolicy(QtGui\&.QSizePolicy\&.Fixed, QtGui\&.QSizePolicy\&.Fixed)
63         sizePolicy\&.setHorizontalStretch(0)
64         sizePolicy\&.setVerticalStretch(0)
65         sizePolicy\&.setHeightForWidth(self\&.timeEdit_saida_antes\&.sizePolicy()\&.hasHeightForWidth())
66         self\&.timeEdit_saida_antes\&.setSizePolicy(sizePolicy)
67         self\&.timeEdit_saida_antes\&.setLocale(QtCore\&.QLocale(QtCore\&.QLocale\&.Portuguese, QtCore\&.QLocale\&.Brazil))
68         self\&.timeEdit_saida_antes\&.setObjectName('timeEdit_saida_antes')
69         self\&.horizontalLayout_2\&.addWidget(self\&.timeEdit_saida_antes)
70         self\&.label_6 = QtGui\&.QLabel(self\&.layoutWidget)
71         self\&.label_6\&.setObjectName('label_6')
72         self\&.horizontalLayout_2\&.addWidget(self\&.label_6)
73         self\&.timeEdit_saida_depois = QtGui\&.QTimeEdit(self\&.layoutWidget)
74         sizePolicy = QtGui\&.QSizePolicy(QtGui\&.QSizePolicy\&.Fixed, QtGui\&.QSizePolicy\&.Fixed)
75         sizePolicy\&.setHorizontalStretch(0)
76         sizePolicy\&.setVerticalStretch(0)
77         sizePolicy\&.setHeightForWidth(self\&.timeEdit_saida_depois\&.sizePolicy()\&.hasHeightForWidth())
78         self\&.timeEdit_saida_depois\&.setSizePolicy(sizePolicy)
79         self\&.timeEdit_saida_depois\&.setLocale(QtCore\&.QLocale(QtCore\&.QLocale\&.Portuguese, QtCore\&.QLocale\&.Brazil))
80         self\&.timeEdit_saida_depois\&.setObjectName('timeEdit_saida_depois')
81         self\&.horizontalLayout_2\&.addWidget(self\&.timeEdit_saida_depois)
82         self\&.label_7 = QtGui\&.QLabel(self\&.layoutWidget)
83         self\&.label_7\&.setObjectName('label_7')
84         self\&.horizontalLayout_2\&.addWidget(self\&.label_7)
85         self\&.verticalLayout\&.addLayout(self\&.horizontalLayout_2)
86         self\&.label_3 = QtGui\&.QLabel(self\&.layoutWidget)
87         self\&.label_3\&.setObjectName('label_3')
88         self\&.verticalLayout\&.addWidget(self\&.label_3)
89         self\&.horizontalLayout_3 = QtGui\&.QHBoxLayout()
90         self\&.horizontalLayout_3\&.setObjectName('horizontalLayout_3')
91         self\&.timeEdit_atraso = QtGui\&.QTimeEdit(self\&.layoutWidget)
92         sizePolicy = QtGui\&.QSizePolicy(QtGui\&.QSizePolicy\&.Fixed, QtGui\&.QSizePolicy\&.Fixed)
93         sizePolicy\&.setHorizontalStretch(0)
94         sizePolicy\&.setVerticalStretch(0)
95         sizePolicy\&.setHeightForWidth(self\&.timeEdit_atraso\&.sizePolicy()\&.hasHeightForWidth())
96         self\&.timeEdit_atraso\&.setSizePolicy(sizePolicy)
97         self\&.timeEdit_atraso\&.setLocale(QtCore\&.QLocale(QtCore\&.QLocale\&.Portuguese, QtCore\&.QLocale\&.Brazil))
98         self\&.timeEdit_atraso\&.setObjectName('timeEdit_atraso')
99         self\&.horizontalLayout_3\&.addWidget(self\&.timeEdit_atraso)
100         spacerItem = QtGui\&.QSpacerItem(40, 20, QtGui\&.QSizePolicy\&.Expanding, QtGui\&.QSizePolicy\&.Minimum)
101         self\&.horizontalLayout_3\&.addItem(spacerItem)
102         self\&.pushButton_salvar = QtGui\&.QPushButton(self\&.layoutWidget)
103         sizePolicy = QtGui\&.QSizePolicy(QtGui\&.QSizePolicy\&.Expanding, QtGui\&.QSizePolicy\&.Fixed)
104         sizePolicy\&.setHorizontalStretch(0)
105         sizePolicy\&.setVerticalStretch(0)
106         sizePolicy\&.setHeightForWidth(self\&.pushButton_salvar\&.sizePolicy()\&.hasHeightForWidth())
107         self\&.pushButton_salvar\&.setSizePolicy(sizePolicy)
108         self\&.pushButton_salvar\&.setObjectName('pushButton_salvar')
109         self\&.horizontalLayout_3\&.addWidget(self\&.pushButton_salvar)
110         spacerItem1 = QtGui\&.QSpacerItem(40, 20, QtGui\&.QSizePolicy\&.Expanding, QtGui\&.QSizePolicy\&.Minimum)
111         self\&.horizontalLayout_3\&.addItem(spacerItem1)
112         self\&.verticalLayout\&.addLayout(self\&.horizontalLayout_3)
113         Tolerancias_Window\&.setCentralWidget(self\&.centralwidget)
114         self\&.menubar = QtGui\&.QMenuBar(Tolerancias_Window)
115         self\&.menubar\&.setGeometry(QtCore\&.QRect(0, 0, 392, 25))
116         self\&.menubar\&.setObjectName('menubar')
117         Tolerancias_Window\&.setMenuBar(self\&.menubar)
118         self\&.statusbar = QtGui\&.QStatusBar(Tolerancias_Window)
119         self\&.statusbar\&.setObjectName('statusbar')
120         Tolerancias_Window\&.setStatusBar(self\&.statusbar)
121 
122         self\&.retranslateUi(Tolerancias_Window)
123         QtCore\&.QMetaObject\&.connectSlotsByName(Tolerancias_Window)

.fi
.SH "Documentação dos dados membro"
.PP 
.SS "\fBcda_tolerancias\&.Ui_Tolerancias_Window::centralwidget\fP"
.PP
Definido na linha 13 do ficheiro cda_tolerancias\&.py\&.
.SS "\fBcda_tolerancias\&.Ui_Tolerancias_Window::horizontalLayout\fP"
.PP
Definido na linha 13 do ficheiro cda_tolerancias\&.py\&.
.SS "\fBcda_tolerancias\&.Ui_Tolerancias_Window::horizontalLayout_2\fP"
.PP
Definido na linha 13 do ficheiro cda_tolerancias\&.py\&.
.SS "\fBcda_tolerancias\&.Ui_Tolerancias_Window::horizontalLayout_3\fP"
.PP
Definido na linha 13 do ficheiro cda_tolerancias\&.py\&.
.SS "\fBcda_tolerancias\&.Ui_Tolerancias_Window::label\fP"
.PP
Definido na linha 13 do ficheiro cda_tolerancias\&.py\&.
.SS "\fBcda_tolerancias\&.Ui_Tolerancias_Window::label_2\fP"
.PP
Definido na linha 13 do ficheiro cda_tolerancias\&.py\&.
.SS "\fBcda_tolerancias\&.Ui_Tolerancias_Window::label_3\fP"
.PP
Definido na linha 13 do ficheiro cda_tolerancias\&.py\&.
.SS "\fBcda_tolerancias\&.Ui_Tolerancias_Window::label_4\fP"
.PP
Definido na linha 13 do ficheiro cda_tolerancias\&.py\&.
.SS "\fBcda_tolerancias\&.Ui_Tolerancias_Window::label_5\fP"
.PP
Definido na linha 13 do ficheiro cda_tolerancias\&.py\&.
.SS "\fBcda_tolerancias\&.Ui_Tolerancias_Window::label_6\fP"
.PP
Definido na linha 13 do ficheiro cda_tolerancias\&.py\&.
.SS "\fBcda_tolerancias\&.Ui_Tolerancias_Window::label_7\fP"
.PP
Definido na linha 13 do ficheiro cda_tolerancias\&.py\&.
.SS "\fBcda_tolerancias\&.Ui_Tolerancias_Window::layoutWidget\fP"
.PP
Definido na linha 13 do ficheiro cda_tolerancias\&.py\&.
.SS "\fBcda_tolerancias\&.Ui_Tolerancias_Window::menubar\fP"
.PP
Definido na linha 13 do ficheiro cda_tolerancias\&.py\&.
.SS "\fBcda_tolerancias\&.Ui_Tolerancias_Window::pushButton_salvar\fP"
.PP
Definido na linha 13 do ficheiro cda_tolerancias\&.py\&.
.SS "\fBcda_tolerancias\&.Ui_Tolerancias_Window::statusbar\fP"
.PP
Definido na linha 13 do ficheiro cda_tolerancias\&.py\&.
.SS "\fBcda_tolerancias\&.Ui_Tolerancias_Window::timeEdit_atraso\fP"
.PP
Definido na linha 13 do ficheiro cda_tolerancias\&.py\&.
.SS "\fBcda_tolerancias\&.Ui_Tolerancias_Window::timeEdit_entrada_antes\fP"
.PP
Definido na linha 13 do ficheiro cda_tolerancias\&.py\&.
.SS "\fBcda_tolerancias\&.Ui_Tolerancias_Window::timeEdit_entrada_depois\fP"
.PP
Definido na linha 13 do ficheiro cda_tolerancias\&.py\&.
.SS "\fBcda_tolerancias\&.Ui_Tolerancias_Window::timeEdit_saida_antes\fP"
.PP
Definido na linha 13 do ficheiro cda_tolerancias\&.py\&.
.SS "\fBcda_tolerancias\&.Ui_Tolerancias_Window::timeEdit_saida_depois\fP"
.PP
Definido na linha 13 do ficheiro cda_tolerancias\&.py\&.
.SS "\fBcda_tolerancias\&.Ui_Tolerancias_Window::verticalLayout\fP"
.PP
Definido na linha 13 do ficheiro cda_tolerancias\&.py\&.

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Controle de Acesso a partir do código fonte\&.
