.TH "cda_relatorios.Ui_Relatorios_Window" 3 "Terça, 24 de Dezembro de 2013" "Version 2" "Controle de Acesso" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cda_relatorios.Ui_Relatorios_Window \- 
.SH SYNOPSIS
.br
.PP
.PP
Herdado por \fBview\&.Relatorios_Window\fP\&.
.SS "Membros públicos"

.in +1c
.ti -1c
.RI "def \fBsetupUi\fP"
.br
.ti -1c
.RI "def \fBretranslateUi\fP"
.br
.in -1c
.SS "Atributos Públicos"

.in +1c
.ti -1c
.RI "\fBcentralwidget\fP"
.br
.ti -1c
.RI "\fBlayoutWidget\fP"
.br
.ti -1c
.RI "\fBverticalLayout\fP"
.br
.ti -1c
.RI "\fBlabel\fP"
.br
.ti -1c
.RI "\fBdateTimeEdit_inicial\fP"
.br
.ti -1c
.RI "\fBlabel_2\fP"
.br
.ti -1c
.RI "\fBdateTimeEdit_final\fP"
.br
.ti -1c
.RI "\fBlayoutWidget1\fP"
.br
.ti -1c
.RI "\fBverticalLayout_2\fP"
.br
.ti -1c
.RI "\fBcheckBox_pontuais\fP"
.br
.ti -1c
.RI "\fBcheckBox_faltosos\fP"
.br
.ti -1c
.RI "\fBcheckBox_atrasados\fP"
.br
.ti -1c
.RI "\fBlayoutWidget2\fP"
.br
.ti -1c
.RI "\fBhorizontalLayout\fP"
.br
.ti -1c
.RI "\fBpushButton_log_porta\fP"
.br
.ti -1c
.RI "\fBpushButton_relatorio_pontos\fP"
.br
.ti -1c
.RI "\fBmenubar\fP"
.br
.in -1c
.SH "Descrição detalhada"
.PP 
Definido na linha 12 do ficheiro cda_relatorios\&.py\&.
.SH "Documentação dos métodos"
.PP 
.SS "def \fBcda_relatorios\&.Ui_Relatorios_Window\&.retranslateUi\fP (self, Relatorios_Window)"
.PP
Definido na linha 84 do ficheiro cda_relatorios\&.py\&.
.PP
.nf
84 
85     def retranslateUi(self, Relatorios_Window):
86         Relatorios_Window\&.setWindowTitle(QtGui\&.QApplication\&.translate('Relatorios_Window', 'Relatorios', None, QtGui\&.QApplication\&.UnicodeUTF8))
87         self\&.label\&.setText(QtGui\&.QApplication\&.translate('Relatorios_Window', 'Data Inicial', None, QtGui\&.QApplication\&.UnicodeUTF8))
88         self\&.label_2\&.setText(QtGui\&.QApplication\&.translate('Relatorios_Window', 'Data Final', None, QtGui\&.QApplication\&.UnicodeUTF8))
89         self\&.checkBox_pontuais\&.setText(QtGui\&.QApplication\&.translate('Relatorios_Window', 'Funcionarios Pontuais', None, QtGui\&.QApplication\&.UnicodeUTF8))
90         self\&.checkBox_faltosos\&.setText(QtGui\&.QApplication\&.translate('Relatorios_Window', 'Funcionarios Faltosos', None, QtGui\&.QApplication\&.UnicodeUTF8))
91         self\&.checkBox_atrasados\&.setText(QtGui\&.QApplication\&.translate('Relatorios_Window', 'Funcionarios Atrasados', None, QtGui\&.QApplication\&.UnicodeUTF8))
92         self\&.pushButton_log_porta\&.setText(QtGui\&.QApplication\&.translate('Relatorios_Window', 'Gerar Logs da Porta', None, QtGui\&.QApplication\&.UnicodeUTF8))
93         self\&.pushButton_relatorio_pontos\&.setText(QtGui\&.QApplication\&.translate('Relatorios_Window', 'Gerar Relatorio Pontos', None, QtGui\&.QApplication\&.UnicodeUTF8))
94 
.fi
.SS "def \fBcda_relatorios\&.Ui_Relatorios_Window\&.setupUi\fP (self, Relatorios_Window)"
.PP
Definido na linha 13 do ficheiro cda_relatorios\&.py\&.
.PP
.nf
13 
14     def setupUi(self, Relatorios_Window):
15         Relatorios_Window\&.setObjectName('Relatorios_Window')
16         Relatorios_Window\&.resize(442, 243)
17         self\&.centralwidget = QtGui\&.QWidget(Relatorios_Window)
18         self\&.centralwidget\&.setObjectName('centralwidget')
19         self\&.layoutWidget = QtGui\&.QWidget(self\&.centralwidget)
20         self\&.layoutWidget\&.setGeometry(QtCore\&.QRect(10, 20, 181, 141))
21         self\&.layoutWidget\&.setObjectName('layoutWidget')
22         self\&.verticalLayout = QtGui\&.QVBoxLayout(self\&.layoutWidget)
23         self\&.verticalLayout\&.setContentsMargins(0, 0, 0, 0)
24         self\&.verticalLayout\&.setObjectName('verticalLayout')
25         self\&.label = QtGui\&.QLabel(self\&.layoutWidget)
26         self\&.label\&.setObjectName('label')
27         self\&.verticalLayout\&.addWidget(self\&.label)
28         self\&.dateTimeEdit_inicial = QtGui\&.QDateTimeEdit(self\&.layoutWidget)
29         self\&.dateTimeEdit_inicial\&.setLocale(QtCore\&.QLocale(QtCore\&.QLocale\&.Portuguese, QtCore\&.QLocale\&.Brazil))
30         self\&.dateTimeEdit_inicial\&.setObjectName('dateTimeEdit_inicial')
31         self\&.verticalLayout\&.addWidget(self\&.dateTimeEdit_inicial)
32         self\&.label_2 = QtGui\&.QLabel(self\&.layoutWidget)
33         self\&.label_2\&.setObjectName('label_2')
34         self\&.verticalLayout\&.addWidget(self\&.label_2)
35         self\&.dateTimeEdit_final = QtGui\&.QDateTimeEdit(self\&.layoutWidget)
36         self\&.dateTimeEdit_final\&.setLocale(QtCore\&.QLocale(QtCore\&.QLocale\&.Portuguese, QtCore\&.QLocale\&.Brazil))
37         self\&.dateTimeEdit_final\&.setObjectName('dateTimeEdit_final')
38         self\&.verticalLayout\&.addWidget(self\&.dateTimeEdit_final)
39         self\&.layoutWidget1 = QtGui\&.QWidget(self\&.centralwidget)
40         self\&.layoutWidget1\&.setGeometry(QtCore\&.QRect(240, 60, 188, 101))
41         self\&.layoutWidget1\&.setObjectName('layoutWidget1')
42         self\&.verticalLayout_2 = QtGui\&.QVBoxLayout(self\&.layoutWidget1)
43         self\&.verticalLayout_2\&.setContentsMargins(0, 0, 0, 0)
44         self\&.verticalLayout_2\&.setObjectName('verticalLayout_2')
45         self\&.checkBox_pontuais = QtGui\&.QCheckBox(self\&.layoutWidget1)
46         self\&.checkBox_pontuais\&.setObjectName('checkBox_pontuais')
47         self\&.verticalLayout_2\&.addWidget(self\&.checkBox_pontuais)
48         self\&.checkBox_faltosos = QtGui\&.QCheckBox(self\&.layoutWidget1)
49         self\&.checkBox_faltosos\&.setObjectName('checkBox_faltosos')
50         self\&.verticalLayout_2\&.addWidget(self\&.checkBox_faltosos)
51         self\&.checkBox_atrasados = QtGui\&.QCheckBox(self\&.layoutWidget1)
52         self\&.checkBox_atrasados\&.setObjectName('checkBox_atrasados')
53         self\&.verticalLayout_2\&.addWidget(self\&.checkBox_atrasados)
54         self\&.layoutWidget2 = QtGui\&.QWidget(self\&.centralwidget)
55         self\&.layoutWidget2\&.setGeometry(QtCore\&.QRect(10, 180, 421, 29))
56         self\&.layoutWidget2\&.setObjectName('layoutWidget2')
57         self\&.horizontalLayout = QtGui\&.QHBoxLayout(self\&.layoutWidget2)
58         self\&.horizontalLayout\&.setContentsMargins(0, 0, 0, 0)
59         self\&.horizontalLayout\&.setObjectName('horizontalLayout')
60         self\&.pushButton_log_porta = QtGui\&.QPushButton(self\&.layoutWidget2)
61         sizePolicy = QtGui\&.QSizePolicy(QtGui\&.QSizePolicy\&.Preferred, QtGui\&.QSizePolicy\&.Fixed)
62         sizePolicy\&.setHorizontalStretch(0)
63         sizePolicy\&.setVerticalStretch(0)
64         sizePolicy\&.setHeightForWidth(self\&.pushButton_log_porta\&.sizePolicy()\&.hasHeightForWidth())
65         self\&.pushButton_log_porta\&.setSizePolicy(sizePolicy)
66         self\&.pushButton_log_porta\&.setObjectName('pushButton_log_porta')
67         self\&.horizontalLayout\&.addWidget(self\&.pushButton_log_porta)
68         self\&.pushButton_relatorio_pontos = QtGui\&.QPushButton(self\&.layoutWidget2)
69         sizePolicy = QtGui\&.QSizePolicy(QtGui\&.QSizePolicy\&.Preferred, QtGui\&.QSizePolicy\&.Fixed)
70         sizePolicy\&.setHorizontalStretch(0)
71         sizePolicy\&.setVerticalStretch(0)
72         sizePolicy\&.setHeightForWidth(self\&.pushButton_relatorio_pontos\&.sizePolicy()\&.hasHeightForWidth())
73         self\&.pushButton_relatorio_pontos\&.setSizePolicy(sizePolicy)
74         self\&.pushButton_relatorio_pontos\&.setObjectName('pushButton_relatorio_pontos')
75         self\&.horizontalLayout\&.addWidget(self\&.pushButton_relatorio_pontos)
76         Relatorios_Window\&.setCentralWidget(self\&.centralwidget)
77         self\&.menubar = QtGui\&.QMenuBar(Relatorios_Window)
78         self\&.menubar\&.setGeometry(QtCore\&.QRect(0, 0, 442, 25))
79         self\&.menubar\&.setObjectName('menubar')
80         Relatorios_Window\&.setMenuBar(self\&.menubar)
81 
82         self\&.retranslateUi(Relatorios_Window)
83         QtCore\&.QMetaObject\&.connectSlotsByName(Relatorios_Window)

.fi
.SH "Documentação dos dados membro"
.PP 
.SS "\fBcda_relatorios\&.Ui_Relatorios_Window::centralwidget\fP"
.PP
Definido na linha 13 do ficheiro cda_relatorios\&.py\&.
.SS "\fBcda_relatorios\&.Ui_Relatorios_Window::checkBox_atrasados\fP"
.PP
Definido na linha 13 do ficheiro cda_relatorios\&.py\&.
.SS "\fBcda_relatorios\&.Ui_Relatorios_Window::checkBox_faltosos\fP"
.PP
Definido na linha 13 do ficheiro cda_relatorios\&.py\&.
.SS "\fBcda_relatorios\&.Ui_Relatorios_Window::checkBox_pontuais\fP"
.PP
Definido na linha 13 do ficheiro cda_relatorios\&.py\&.
.SS "\fBcda_relatorios\&.Ui_Relatorios_Window::dateTimeEdit_final\fP"
.PP
Definido na linha 13 do ficheiro cda_relatorios\&.py\&.
.SS "\fBcda_relatorios\&.Ui_Relatorios_Window::dateTimeEdit_inicial\fP"
.PP
Definido na linha 13 do ficheiro cda_relatorios\&.py\&.
.SS "\fBcda_relatorios\&.Ui_Relatorios_Window::horizontalLayout\fP"
.PP
Definido na linha 13 do ficheiro cda_relatorios\&.py\&.
.SS "\fBcda_relatorios\&.Ui_Relatorios_Window::label\fP"
.PP
Definido na linha 13 do ficheiro cda_relatorios\&.py\&.
.SS "\fBcda_relatorios\&.Ui_Relatorios_Window::label_2\fP"
.PP
Definido na linha 13 do ficheiro cda_relatorios\&.py\&.
.SS "\fBcda_relatorios\&.Ui_Relatorios_Window::layoutWidget\fP"
.PP
Definido na linha 13 do ficheiro cda_relatorios\&.py\&.
.SS "\fBcda_relatorios\&.Ui_Relatorios_Window::layoutWidget1\fP"
.PP
Definido na linha 13 do ficheiro cda_relatorios\&.py\&.
.SS "\fBcda_relatorios\&.Ui_Relatorios_Window::layoutWidget2\fP"
.PP
Definido na linha 13 do ficheiro cda_relatorios\&.py\&.
.SS "\fBcda_relatorios\&.Ui_Relatorios_Window::menubar\fP"
.PP
Definido na linha 13 do ficheiro cda_relatorios\&.py\&.
.SS "\fBcda_relatorios\&.Ui_Relatorios_Window::pushButton_log_porta\fP"
.PP
Definido na linha 13 do ficheiro cda_relatorios\&.py\&.
.SS "\fBcda_relatorios\&.Ui_Relatorios_Window::pushButton_relatorio_pontos\fP"
.PP
Definido na linha 13 do ficheiro cda_relatorios\&.py\&.
.SS "\fBcda_relatorios\&.Ui_Relatorios_Window::verticalLayout\fP"
.PP
Definido na linha 13 do ficheiro cda_relatorios\&.py\&.
.SS "\fBcda_relatorios\&.Ui_Relatorios_Window::verticalLayout_2\fP"
.PP
Definido na linha 13 do ficheiro cda_relatorios\&.py\&.

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Controle de Acesso a partir do código fonte\&.
