.TH "cda_horarios.Ui_Horarios_Window" 3 "Terça, 24 de Dezembro de 2013" "Version 2" "Controle de Acesso" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cda_horarios.Ui_Horarios_Window \- 
.SH SYNOPSIS
.br
.PP
.PP
Herdado por \fBview\&.Horarios_Window\fP\&.
.SS "Membros públicos"

.in +1c
.ti -1c
.RI "def \fBsetupUi\fP"
.br
.ti -1c
.RI "def \fBretranslateUi\fP"
.br
.in -1c
.SS "Atributos Públicos"

.in +1c
.ti -1c
.RI "\fBcentralwidget\fP"
.br
.ti -1c
.RI "\fBtableView_horarios\fP"
.br
.in -1c
.SH "Descrição detalhada"
.PP 
Definido na linha 12 do ficheiro cda_horarios\&.py\&.
.SH "Documentação dos métodos"
.PP 
.SS "def \fBcda_horarios\&.Ui_Horarios_Window\&.retranslateUi\fP (self, Horarios_Window)"
.PP
Definido na linha 32 do ficheiro cda_horarios\&.py\&.
.PP
.nf
32 
33     def retranslateUi(self, Horarios_Window):
34         Horarios_Window\&.setWindowTitle(QtGui\&.QApplication\&.translate('Horarios_Window', 'Horarios', None, QtGui\&.QApplication\&.UnicodeUTF8))
35 
.fi
.SS "def \fBcda_horarios\&.Ui_Horarios_Window\&.setupUi\fP (self, Horarios_Window)"
.PP
Definido na linha 13 do ficheiro cda_horarios\&.py\&.
.PP
.nf
13 
14     def setupUi(self, Horarios_Window):
15         Horarios_Window\&.setObjectName('Horarios_Window')
16         Horarios_Window\&.resize(640, 594)
17         sizePolicy = QtGui\&.QSizePolicy(QtGui\&.QSizePolicy\&.Preferred, QtGui\&.QSizePolicy\&.Preferred)
18         sizePolicy\&.setHorizontalStretch(0)
19         sizePolicy\&.setVerticalStretch(0)
20         sizePolicy\&.setHeightForWidth(Horarios_Window\&.sizePolicy()\&.hasHeightForWidth())
21         Horarios_Window\&.setSizePolicy(sizePolicy)
22         Horarios_Window\&.setLocale(QtCore\&.QLocale(QtCore\&.QLocale\&.Portuguese, QtCore\&.QLocale\&.Brazil))
23         self\&.centralwidget = QtGui\&.QWidget(Horarios_Window)
24         self\&.centralwidget\&.setObjectName('centralwidget')
25         self\&.tableView_horarios = QtGui\&.QTableView(self\&.centralwidget)
26         self\&.tableView_horarios\&.setGeometry(QtCore\&.QRect(10, 10, 621, 571))
27         self\&.tableView_horarios\&.setObjectName('tableView_horarios')
28         Horarios_Window\&.setCentralWidget(self\&.centralwidget)
29 
30         self\&.retranslateUi(Horarios_Window)
31         QtCore\&.QMetaObject\&.connectSlotsByName(Horarios_Window)

.fi
.SH "Documentação dos dados membro"
.PP 
.SS "\fBcda_horarios\&.Ui_Horarios_Window::centralwidget\fP"
.PP
Definido na linha 13 do ficheiro cda_horarios\&.py\&.
.SS "\fBcda_horarios\&.Ui_Horarios_Window::tableView_horarios\fP"
.PP
Definido na linha 13 do ficheiro cda_horarios\&.py\&.

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Controle de Acesso a partir do código fonte\&.
