.TH "cda_funcionarios.Ui_Add_Funcionarios_Window" 3 "Terça, 24 de Dezembro de 2013" "Version 2" "Controle de Acesso" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cda_funcionarios.Ui_Add_Funcionarios_Window \- 
.SH SYNOPSIS
.br
.PP
.PP
Herdado por \fBview\&.Funcionarios_Window\fP\&.
.SS "Membros públicos"

.in +1c
.ti -1c
.RI "def \fBsetupUi\fP"
.br
.ti -1c
.RI "def \fBretranslateUi\fP"
.br
.in -1c
.SS "Atributos Públicos"

.in +1c
.ti -1c
.RI "\fBcentralwidget\fP"
.br
.ti -1c
.RI "\fBpushButton_adicionar\fP"
.br
.ti -1c
.RI "\fBlayoutWidget\fP"
.br
.ti -1c
.RI "\fBverticalLayout\fP"
.br
.ti -1c
.RI "\fBhorizontalLayout_2\fP"
.br
.ti -1c
.RI "\fBlabel_2\fP"
.br
.ti -1c
.RI "\fBlineEdit_nome\fP"
.br
.ti -1c
.RI "\fBhorizontalLayout\fP"
.br
.ti -1c
.RI "\fBlabel_3\fP"
.br
.ti -1c
.RI "\fBlineEdit_matricula\fP"
.br
.ti -1c
.RI "\fBhorizontalLayout_3\fP"
.br
.ti -1c
.RI "\fBlabel_4\fP"
.br
.ti -1c
.RI "\fBpushButton_obter_rfid\fP"
.br
.ti -1c
.RI "\fBlabel_RFID\fP"
.br
.ti -1c
.RI "\fBhorizontalLayout_5\fP"
.br
.ti -1c
.RI "\fBlabel_7\fP"
.br
.ti -1c
.RI "\fBcomboBox_dias_semana\fP"
.br
.ti -1c
.RI "\fBhorizontalLayout_4\fP"
.br
.ti -1c
.RI "\fBlabel_5\fP"
.br
.ti -1c
.RI "\fBtimeEdit_entrada\fP"
.br
.ti -1c
.RI "\fBlabel_6\fP"
.br
.ti -1c
.RI "\fBtimeEdit_saida\fP"
.br
.ti -1c
.RI "\fBtableView_horarios\fP"
.br
.ti -1c
.RI "\fBhorizontalLayout_6\fP"
.br
.ti -1c
.RI "\fBpushButton_adicionar_horario\fP"
.br
.ti -1c
.RI "\fBpushButton_remover_horario\fP"
.br
.ti -1c
.RI "\fBlayoutWidget1\fP"
.br
.ti -1c
.RI "\fBverticalLayout_2\fP"
.br
.ti -1c
.RI "\fBlabel\fP"
.br
.ti -1c
.RI "\fBlistView_funcionarios\fP"
.br
.ti -1c
.RI "\fBmenubar\fP"
.br
.in -1c
.SH "Descrição detalhada"
.PP 
Definido na linha 12 do ficheiro cda_funcionarios\&.py\&.
.SH "Documentação dos métodos"
.PP 
.SS "def \fBcda_funcionarios\&.Ui_Add_Funcionarios_Window\&.retranslateUi\fP (self, Add_Funcionarios_Window)"
.PP
Definido na linha 157 do ficheiro cda_funcionarios\&.py\&.
.PP
.nf
157 
158     def retranslateUi(self, Add_Funcionarios_Window):
159         Add_Funcionarios_Window\&.setWindowTitle(QtGui\&.QApplication\&.translate('Add_Funcionarios_Window', 'Adicionar Funcionarios', None, QtGui\&.QApplication\&.UnicodeUTF8))
160         self\&.pushButton_adicionar\&.setText(QtGui\&.QApplication\&.translate('Add_Funcionarios_Window', 'Adicionar Funcionario', None, QtGui\&.QApplication\&.UnicodeUTF8))
161         self\&.label_2\&.setText(QtGui\&.QApplication\&.translate('Add_Funcionarios_Window', 'Nome', None, QtGui\&.QApplication\&.UnicodeUTF8))
162         self\&.label_3\&.setText(QtGui\&.QApplication\&.translate('Add_Funcionarios_Window', 'Matricula', None, QtGui\&.QApplication\&.UnicodeUTF8))
163         self\&.label_4\&.setText(QtGui\&.QApplication\&.translate('Add_Funcionarios_Window', 'RFID', None, QtGui\&.QApplication\&.UnicodeUTF8))
164         self\&.pushButton_obter_rfid\&.setText(QtGui\&.QApplication\&.translate('Add_Funcionarios_Window', 'Obter RFID', None, QtGui\&.QApplication\&.UnicodeUTF8))
165         self\&.label_7\&.setText(QtGui\&.QApplication\&.translate('Add_Funcionarios_Window', 'Dia da Semana', None, QtGui\&.QApplication\&.UnicodeUTF8))
166         self\&.comboBox_dias_semana\&.setItemText(0, QtGui\&.QApplication\&.translate('Add_Funcionarios_Window', 'Domingo', None, QtGui\&.QApplication\&.UnicodeUTF8))
167         self\&.comboBox_dias_semana\&.setItemText(1, QtGui\&.QApplication\&.translate('Add_Funcionarios_Window', 'Segunda', None, QtGui\&.QApplication\&.UnicodeUTF8))
168         self\&.comboBox_dias_semana\&.setItemText(2, QtGui\&.QApplication\&.translate('Add_Funcionarios_Window', 'Terça', None, QtGui\&.QApplication\&.UnicodeUTF8))
169         self\&.comboBox_dias_semana\&.setItemText(3, QtGui\&.QApplication\&.translate('Add_Funcionarios_Window', 'Quarta', None, QtGui\&.QApplication\&.UnicodeUTF8))
170         self\&.comboBox_dias_semana\&.setItemText(4, QtGui\&.QApplication\&.translate('Add_Funcionarios_Window', 'Quinta', None, QtGui\&.QApplication\&.UnicodeUTF8))
171         self\&.comboBox_dias_semana\&.setItemText(5, QtGui\&.QApplication\&.translate('Add_Funcionarios_Window', 'Sexta', None, QtGui\&.QApplication\&.UnicodeUTF8))
172         self\&.comboBox_dias_semana\&.setItemText(6, QtGui\&.QApplication\&.translate('Add_Funcionarios_Window', 'Sabado', None, QtGui\&.QApplication\&.UnicodeUTF8))
173         self\&.label_5\&.setText(QtGui\&.QApplication\&.translate('Add_Funcionarios_Window', 'Entrada', None, QtGui\&.QApplication\&.UnicodeUTF8))
174         self\&.label_6\&.setText(QtGui\&.QApplication\&.translate('Add_Funcionarios_Window', 'Saida', None, QtGui\&.QApplication\&.UnicodeUTF8))
175         self\&.pushButton_adicionar_horario\&.setText(QtGui\&.QApplication\&.translate('Add_Funcionarios_Window', 'Adicionar Horario', None, QtGui\&.QApplication\&.UnicodeUTF8))
176         self\&.pushButton_remover_horario\&.setText(QtGui\&.QApplication\&.translate('Add_Funcionarios_Window', 'Remover Horario', None, QtGui\&.QApplication\&.UnicodeUTF8))
177         self\&.label\&.setText(QtGui\&.QApplication\&.translate('Add_Funcionarios_Window', 'Funcionarios Cadastrados', None, QtGui\&.QApplication\&.UnicodeUTF8))
178 
.fi
.SS "def \fBcda_funcionarios\&.Ui_Add_Funcionarios_Window\&.setupUi\fP (self, Add_Funcionarios_Window)"
.PP
Definido na linha 13 do ficheiro cda_funcionarios\&.py\&.
.PP
.nf
13 
14     def setupUi(self, Add_Funcionarios_Window):
15         Add_Funcionarios_Window\&.setObjectName('Add_Funcionarios_Window')
16         Add_Funcionarios_Window\&.resize(674, 483)
17         Add_Funcionarios_Window\&.setLocale(QtCore\&.QLocale(QtCore\&.QLocale\&.Portuguese, QtCore\&.QLocale\&.Brazil))
18         self\&.centralwidget = QtGui\&.QWidget(Add_Funcionarios_Window)
19         self\&.centralwidget\&.setObjectName('centralwidget')
20         self\&.pushButton_adicionar = QtGui\&.QPushButton(self\&.centralwidget)
21         self\&.pushButton_adicionar\&.setGeometry(QtCore\&.QRect(480, 410, 181, 27))
22         self\&.pushButton_adicionar\&.setObjectName('pushButton_adicionar')
23         self\&.layoutWidget = QtGui\&.QWidget(self\&.centralwidget)
24         self\&.layoutWidget\&.setGeometry(QtCore\&.QRect(290, 40, 371, 341))
25         self\&.layoutWidget\&.setObjectName('layoutWidget')
26         self\&.verticalLayout = QtGui\&.QVBoxLayout(self\&.layoutWidget)
27         self\&.verticalLayout\&.setContentsMargins(0, 0, 0, 0)
28         self\&.verticalLayout\&.setObjectName('verticalLayout')
29         self\&.horizontalLayout_2 = QtGui\&.QHBoxLayout()
30         self\&.horizontalLayout_2\&.setObjectName('horizontalLayout_2')
31         self\&.label_2 = QtGui\&.QLabel(self\&.layoutWidget)
32         self\&.label_2\&.setObjectName('label_2')
33         self\&.horizontalLayout_2\&.addWidget(self\&.label_2)
34         self\&.lineEdit_nome = QtGui\&.QLineEdit(self\&.layoutWidget)
35         sizePolicy = QtGui\&.QSizePolicy(QtGui\&.QSizePolicy\&.Preferred, QtGui\&.QSizePolicy\&.Fixed)
36         sizePolicy\&.setHorizontalStretch(0)
37         sizePolicy\&.setVerticalStretch(0)
38         sizePolicy\&.setHeightForWidth(self\&.lineEdit_nome\&.sizePolicy()\&.hasHeightForWidth())
39         self\&.lineEdit_nome\&.setSizePolicy(sizePolicy)
40         self\&.lineEdit_nome\&.setObjectName('lineEdit_nome')
41         self\&.horizontalLayout_2\&.addWidget(self\&.lineEdit_nome)
42         self\&.verticalLayout\&.addLayout(self\&.horizontalLayout_2)
43         self\&.horizontalLayout = QtGui\&.QHBoxLayout()
44         self\&.horizontalLayout\&.setObjectName('horizontalLayout')
45         self\&.label_3 = QtGui\&.QLabel(self\&.layoutWidget)
46         self\&.label_3\&.setObjectName('label_3')
47         self\&.horizontalLayout\&.addWidget(self\&.label_3)
48         self\&.lineEdit_matricula = QtGui\&.QLineEdit(self\&.layoutWidget)
49         sizePolicy = QtGui\&.QSizePolicy(QtGui\&.QSizePolicy\&.Preferred, QtGui\&.QSizePolicy\&.Fixed)
50         sizePolicy\&.setHorizontalStretch(0)
51         sizePolicy\&.setVerticalStretch(0)
52         sizePolicy\&.setHeightForWidth(self\&.lineEdit_matricula\&.sizePolicy()\&.hasHeightForWidth())
53         self\&.lineEdit_matricula\&.setSizePolicy(sizePolicy)
54         self\&.lineEdit_matricula\&.setObjectName('lineEdit_matricula')
55         self\&.horizontalLayout\&.addWidget(self\&.lineEdit_matricula)
56         self\&.verticalLayout\&.addLayout(self\&.horizontalLayout)
57         self\&.horizontalLayout_3 = QtGui\&.QHBoxLayout()
58         self\&.horizontalLayout_3\&.setObjectName('horizontalLayout_3')
59         self\&.label_4 = QtGui\&.QLabel(self\&.layoutWidget)
60         self\&.label_4\&.setObjectName('label_4')
61         self\&.horizontalLayout_3\&.addWidget(self\&.label_4)
62         self\&.pushButton_obter_rfid = QtGui\&.QPushButton(self\&.layoutWidget)
63         self\&.pushButton_obter_rfid\&.setObjectName('pushButton_obter_rfid')
64         self\&.horizontalLayout_3\&.addWidget(self\&.pushButton_obter_rfid)
65         self\&.verticalLayout\&.addLayout(self\&.horizontalLayout_3)
66         self\&.label_RFID = QtGui\&.QLabel(self\&.layoutWidget)
67         self\&.label_RFID\&.setText('')
68         self\&.label_RFID\&.setObjectName('label_RFID')
69         self\&.verticalLayout\&.addWidget(self\&.label_RFID)
70         self\&.horizontalLayout_5 = QtGui\&.QHBoxLayout()
71         self\&.horizontalLayout_5\&.setObjectName('horizontalLayout_5')
72         self\&.label_7 = QtGui\&.QLabel(self\&.layoutWidget)
73         self\&.label_7\&.setObjectName('label_7')
74         self\&.horizontalLayout_5\&.addWidget(self\&.label_7)
75         self\&.comboBox_dias_semana = QtGui\&.QComboBox(self\&.layoutWidget)
76         self\&.comboBox_dias_semana\&.setObjectName('comboBox_dias_semana')
77         self\&.comboBox_dias_semana\&.addItem('')
78         self\&.comboBox_dias_semana\&.addItem('')
79         self\&.comboBox_dias_semana\&.addItem('')
80         self\&.comboBox_dias_semana\&.addItem('')
81         self\&.comboBox_dias_semana\&.addItem('')
82         self\&.comboBox_dias_semana\&.addItem('')
83         self\&.comboBox_dias_semana\&.addItem('')
84         self\&.horizontalLayout_5\&.addWidget(self\&.comboBox_dias_semana)
85         self\&.verticalLayout\&.addLayout(self\&.horizontalLayout_5)
86         self\&.horizontalLayout_4 = QtGui\&.QHBoxLayout()
87         self\&.horizontalLayout_4\&.setObjectName('horizontalLayout_4')
88         self\&.label_5 = QtGui\&.QLabel(self\&.layoutWidget)
89         sizePolicy = QtGui\&.QSizePolicy(QtGui\&.QSizePolicy\&.Fixed, QtGui\&.QSizePolicy\&.Preferred)
90         sizePolicy\&.setHorizontalStretch(0)
91         sizePolicy\&.setVerticalStretch(0)
92         sizePolicy\&.setHeightForWidth(self\&.label_5\&.sizePolicy()\&.hasHeightForWidth())
93         self\&.label_5\&.setSizePolicy(sizePolicy)
94         self\&.label_5\&.setLayoutDirection(QtCore\&.Qt\&.LeftToRight)
95         self\&.label_5\&.setAlignment(QtCore\&.Qt\&.AlignRight|QtCore\&.Qt\&.AlignTrailing|QtCore\&.Qt\&.AlignVCenter)
96         self\&.label_5\&.setObjectName('label_5')
97         self\&.horizontalLayout_4\&.addWidget(self\&.label_5)
98         self\&.timeEdit_entrada = QtGui\&.QTimeEdit(self\&.layoutWidget)
99         self\&.timeEdit_entrada\&.setObjectName('timeEdit_entrada')
100         self\&.horizontalLayout_4\&.addWidget(self\&.timeEdit_entrada)
101         spacerItem = QtGui\&.QSpacerItem(40, 20, QtGui\&.QSizePolicy\&.Expanding, QtGui\&.QSizePolicy\&.Minimum)
102         self\&.horizontalLayout_4\&.addItem(spacerItem)
103         self\&.label_6 = QtGui\&.QLabel(self\&.layoutWidget)
104         sizePolicy = QtGui\&.QSizePolicy(QtGui\&.QSizePolicy\&.Fixed, QtGui\&.QSizePolicy\&.Preferred)
105         sizePolicy\&.setHorizontalStretch(0)
106         sizePolicy\&.setVerticalStretch(0)
107         sizePolicy\&.setHeightForWidth(self\&.label_6\&.sizePolicy()\&.hasHeightForWidth())
108         self\&.label_6\&.setSizePolicy(sizePolicy)
109         self\&.label_6\&.setAlignment(QtCore\&.Qt\&.AlignRight|QtCore\&.Qt\&.AlignTrailing|QtCore\&.Qt\&.AlignVCenter)
110         self\&.label_6\&.setObjectName('label_6')
111         self\&.horizontalLayout_4\&.addWidget(self\&.label_6)
112         self\&.timeEdit_saida = QtGui\&.QTimeEdit(self\&.layoutWidget)
113         self\&.timeEdit_saida\&.setObjectName('timeEdit_saida')
114         self\&.horizontalLayout_4\&.addWidget(self\&.timeEdit_saida)
115         self\&.verticalLayout\&.addLayout(self\&.horizontalLayout_4)
116         self\&.tableView_horarios = QtGui\&.QTableView(self\&.layoutWidget)
117         self\&.tableView_horarios\&.setObjectName('tableView_horarios')
118         self\&.verticalLayout\&.addWidget(self\&.tableView_horarios)
119         self\&.horizontalLayout_6 = QtGui\&.QHBoxLayout()
120         self\&.horizontalLayout_6\&.setObjectName('horizontalLayout_6')
121         self\&.pushButton_adicionar_horario = QtGui\&.QPushButton(self\&.layoutWidget)
122         self\&.pushButton_adicionar_horario\&.setObjectName('pushButton_adicionar_horario')
123         self\&.horizontalLayout_6\&.addWidget(self\&.pushButton_adicionar_horario)
124         self\&.pushButton_remover_horario = QtGui\&.QPushButton(self\&.layoutWidget)
125         self\&.pushButton_remover_horario\&.setObjectName('pushButton_remover_horario')
126         self\&.horizontalLayout_6\&.addWidget(self\&.pushButton_remover_horario)
127         self\&.verticalLayout\&.addLayout(self\&.horizontalLayout_6)
128         self\&.layoutWidget1 = QtGui\&.QWidget(self\&.centralwidget)
129         self\&.layoutWidget1\&.setGeometry(QtCore\&.QRect(20, 20, 258, 421))
130         self\&.layoutWidget1\&.setObjectName('layoutWidget1')
131         self\&.verticalLayout_2 = QtGui\&.QVBoxLayout(self\&.layoutWidget1)
132         self\&.verticalLayout_2\&.setContentsMargins(0, 0, 0, 0)
133         self\&.verticalLayout_2\&.setObjectName('verticalLayout_2')
134         self\&.label = QtGui\&.QLabel(self\&.layoutWidget1)
135         self\&.label\&.setObjectName('label')
136         self\&.verticalLayout_2\&.addWidget(self\&.label)
137         self\&.listView_funcionarios = QtGui\&.QListView(self\&.layoutWidget1)
138         self\&.listView_funcionarios\&.setObjectName('listView_funcionarios')
139         self\&.verticalLayout_2\&.addWidget(self\&.listView_funcionarios)
140         Add_Funcionarios_Window\&.setCentralWidget(self\&.centralwidget)
141         self\&.menubar = QtGui\&.QMenuBar(Add_Funcionarios_Window)
142         self\&.menubar\&.setGeometry(QtCore\&.QRect(0, 0, 674, 25))
143         self\&.menubar\&.setObjectName('menubar')
144         Add_Funcionarios_Window\&.setMenuBar(self\&.menubar)
145 
146         self\&.retranslateUi(Add_Funcionarios_Window)
147         QtCore\&.QMetaObject\&.connectSlotsByName(Add_Funcionarios_Window)
148         Add_Funcionarios_Window\&.setTabOrder(self\&.lineEdit_nome, self\&.lineEdit_matricula)
149         Add_Funcionarios_Window\&.setTabOrder(self\&.lineEdit_matricula, self\&.pushButton_obter_rfid)
150         Add_Funcionarios_Window\&.setTabOrder(self\&.pushButton_obter_rfid, self\&.comboBox_dias_semana)
151         Add_Funcionarios_Window\&.setTabOrder(self\&.comboBox_dias_semana, self\&.timeEdit_entrada)
152         Add_Funcionarios_Window\&.setTabOrder(self\&.timeEdit_entrada, self\&.timeEdit_saida)
153         Add_Funcionarios_Window\&.setTabOrder(self\&.timeEdit_saida, self\&.pushButton_adicionar_horario)
154         Add_Funcionarios_Window\&.setTabOrder(self\&.pushButton_adicionar_horario, self\&.pushButton_remover_horario)
155         Add_Funcionarios_Window\&.setTabOrder(self\&.pushButton_remover_horario, self\&.pushButton_adicionar)
156         Add_Funcionarios_Window\&.setTabOrder(self\&.pushButton_adicionar, self\&.listView_funcionarios)

.fi
.SH "Documentação dos dados membro"
.PP 
.SS "\fBcda_funcionarios\&.Ui_Add_Funcionarios_Window::centralwidget\fP"
.PP
Definido na linha 13 do ficheiro cda_funcionarios\&.py\&.
.SS "\fBcda_funcionarios\&.Ui_Add_Funcionarios_Window::comboBox_dias_semana\fP"
.PP
Definido na linha 13 do ficheiro cda_funcionarios\&.py\&.
.SS "\fBcda_funcionarios\&.Ui_Add_Funcionarios_Window::horizontalLayout\fP"
.PP
Definido na linha 13 do ficheiro cda_funcionarios\&.py\&.
.SS "\fBcda_funcionarios\&.Ui_Add_Funcionarios_Window::horizontalLayout_2\fP"
.PP
Definido na linha 13 do ficheiro cda_funcionarios\&.py\&.
.SS "\fBcda_funcionarios\&.Ui_Add_Funcionarios_Window::horizontalLayout_3\fP"
.PP
Definido na linha 13 do ficheiro cda_funcionarios\&.py\&.
.SS "\fBcda_funcionarios\&.Ui_Add_Funcionarios_Window::horizontalLayout_4\fP"
.PP
Definido na linha 13 do ficheiro cda_funcionarios\&.py\&.
.SS "\fBcda_funcionarios\&.Ui_Add_Funcionarios_Window::horizontalLayout_5\fP"
.PP
Definido na linha 13 do ficheiro cda_funcionarios\&.py\&.
.SS "\fBcda_funcionarios\&.Ui_Add_Funcionarios_Window::horizontalLayout_6\fP"
.PP
Definido na linha 13 do ficheiro cda_funcionarios\&.py\&.
.SS "\fBcda_funcionarios\&.Ui_Add_Funcionarios_Window::label\fP"
.PP
Definido na linha 13 do ficheiro cda_funcionarios\&.py\&.
.SS "\fBcda_funcionarios\&.Ui_Add_Funcionarios_Window::label_2\fP"
.PP
Definido na linha 13 do ficheiro cda_funcionarios\&.py\&.
.SS "\fBcda_funcionarios\&.Ui_Add_Funcionarios_Window::label_3\fP"
.PP
Definido na linha 13 do ficheiro cda_funcionarios\&.py\&.
.SS "\fBcda_funcionarios\&.Ui_Add_Funcionarios_Window::label_4\fP"
.PP
Definido na linha 13 do ficheiro cda_funcionarios\&.py\&.
.SS "\fBcda_funcionarios\&.Ui_Add_Funcionarios_Window::label_5\fP"
.PP
Definido na linha 13 do ficheiro cda_funcionarios\&.py\&.
.SS "\fBcda_funcionarios\&.Ui_Add_Funcionarios_Window::label_6\fP"
.PP
Definido na linha 13 do ficheiro cda_funcionarios\&.py\&.
.SS "\fBcda_funcionarios\&.Ui_Add_Funcionarios_Window::label_7\fP"
.PP
Definido na linha 13 do ficheiro cda_funcionarios\&.py\&.
.SS "\fBcda_funcionarios\&.Ui_Add_Funcionarios_Window::label_RFID\fP"
.PP
Definido na linha 13 do ficheiro cda_funcionarios\&.py\&.
.SS "\fBcda_funcionarios\&.Ui_Add_Funcionarios_Window::layoutWidget\fP"
.PP
Definido na linha 13 do ficheiro cda_funcionarios\&.py\&.
.SS "\fBcda_funcionarios\&.Ui_Add_Funcionarios_Window::layoutWidget1\fP"
.PP
Definido na linha 13 do ficheiro cda_funcionarios\&.py\&.
.SS "\fBcda_funcionarios\&.Ui_Add_Funcionarios_Window::lineEdit_matricula\fP"
.PP
Definido na linha 13 do ficheiro cda_funcionarios\&.py\&.
.SS "\fBcda_funcionarios\&.Ui_Add_Funcionarios_Window::lineEdit_nome\fP"
.PP
Definido na linha 13 do ficheiro cda_funcionarios\&.py\&.
.SS "\fBcda_funcionarios\&.Ui_Add_Funcionarios_Window::listView_funcionarios\fP"
.PP
Definido na linha 13 do ficheiro cda_funcionarios\&.py\&.
.SS "\fBcda_funcionarios\&.Ui_Add_Funcionarios_Window::menubar\fP"
.PP
Definido na linha 13 do ficheiro cda_funcionarios\&.py\&.
.SS "\fBcda_funcionarios\&.Ui_Add_Funcionarios_Window::pushButton_adicionar\fP"
.PP
Definido na linha 13 do ficheiro cda_funcionarios\&.py\&.
.SS "\fBcda_funcionarios\&.Ui_Add_Funcionarios_Window::pushButton_adicionar_horario\fP"
.PP
Definido na linha 13 do ficheiro cda_funcionarios\&.py\&.
.SS "\fBcda_funcionarios\&.Ui_Add_Funcionarios_Window::pushButton_obter_rfid\fP"
.PP
Definido na linha 13 do ficheiro cda_funcionarios\&.py\&.
.SS "\fBcda_funcionarios\&.Ui_Add_Funcionarios_Window::pushButton_remover_horario\fP"
.PP
Definido na linha 13 do ficheiro cda_funcionarios\&.py\&.
.SS "\fBcda_funcionarios\&.Ui_Add_Funcionarios_Window::tableView_horarios\fP"
.PP
Definido na linha 13 do ficheiro cda_funcionarios\&.py\&.
.SS "\fBcda_funcionarios\&.Ui_Add_Funcionarios_Window::timeEdit_entrada\fP"
.PP
Definido na linha 13 do ficheiro cda_funcionarios\&.py\&.
.SS "\fBcda_funcionarios\&.Ui_Add_Funcionarios_Window::timeEdit_saida\fP"
.PP
Definido na linha 13 do ficheiro cda_funcionarios\&.py\&.
.SS "\fBcda_funcionarios\&.Ui_Add_Funcionarios_Window::verticalLayout\fP"
.PP
Definido na linha 13 do ficheiro cda_funcionarios\&.py\&.
.SS "\fBcda_funcionarios\&.Ui_Add_Funcionarios_Window::verticalLayout_2\fP"
.PP
Definido na linha 13 do ficheiro cda_funcionarios\&.py\&.

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Controle de Acesso a partir do código fonte\&.
