.TH "instalar" 3 "Terça, 24 de Dezembro de 2013" "Version 2" "Controle de Acesso" \" -*- nroff -*-
.ad l
.nh
.SH NAME
instalar \- 
.SH SYNOPSIS
.br
.PP
.SS "Componentes"

.in +1c
.ti -1c
.RI "class \fBConnect_MySQL\fP"
.br
.RI "\fIClasse de conexão e acesso ao banco de dados\&. \fP"
.ti -1c
.RI "class \fBInstalar\fP"
.br
.in -1c
.SS "Variáveis"

.in +1c
.ti -1c
.RI "tuple \fBdb\fP = \fBConnect_MySQL\fP('localhost','root','42')"
.br
.ti -1c
.RI "tuple \fBins\fP = \fBInstalar\fP(\fBdb\fP)"
.br
.in -1c
.SH "Documentação das variáveis"
.PP 
.SS "tuple \fBinstalar::db\fP = \fBConnect_MySQL\fP('localhost','root','42')"
.PP
Definido na linha 63 do ficheiro instalar\&.py\&.
.SS "tuple \fBinstalar::ins\fP = \fBInstalar\fP(\fBdb\fP)"
.PP
Definido na linha 64 do ficheiro instalar\&.py\&.
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Controle de Acesso a partir do código fonte\&.
