.TH "instalar.Instalar" 3 "Terça, 24 de Dezembro de 2013" "Version 2" "Controle de Acesso" \" -*- nroff -*-
.ad l
.nh
.SH NAME
instalar.Instalar \- 
.SH SYNOPSIS
.br
.PP
.SS "Membros públicos"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBcriar\fP"
.br
.ti -1c
.RI "def \fBconfigurar\fP"
.br
.in -1c
.SS "Atributos Públicos"

.in +1c
.ti -1c
.RI "\fBdb\fP"
.br
.in -1c
.SH "Descrição detalhada"
.PP 
Definido na linha 49 do ficheiro instalar\&.py\&.
.SH "Documentação dos Construtores & Destrutor"
.PP 
.SS "def \fBinstalar\&.Instalar\&.__init__\fP (self, db)"
.PP
Definido na linha 50 do ficheiro instalar\&.py\&.
.PP
.nf
50 
51     def __init__(self,db):
        self\&.db=db
.fi
.SH "Documentação dos métodos"
.PP 
.SS "def \fBinstalar\&.Instalar\&.configurar\fP (self)"
.PP
Definido na linha 54 do ficheiro instalar\&.py\&.
.PP
.nf
54 
55     def configurar(self):
56         db\&.criar_Configuracoes('adm_senha',criptografar_Senha('42'))
57         db\&.criar_Configuracoes('tol_ent_ant','00:30:00')
58         db\&.criar_Configuracoes('tol_ent_dep','00:30:00')
59         db\&.criar_Configuracoes('tol_sai_ant','00:30:00')
60         db\&.criar_Configuracoes('tol_sai_dep','00:30:00')
61         db\&.criar_Configuracoes('considerar_atraso','00:10:00')

.fi
.SS "def \fBinstalar\&.Instalar\&.criar\fP (self)"
.PP
Definido na linha 52 do ficheiro instalar\&.py\&.
.PP
.nf
52 
53     def criar(self):      
        db\&.criar_Tabelas()
.fi
.SH "Documentação dos dados membro"
.PP 
.SS "\fBinstalar\&.Instalar::db\fP"
.PP
Definido na linha 50 do ficheiro instalar\&.py\&.

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Controle de Acesso a partir do código fonte\&.
