.TH "model_mysql.py" 3 "Terça, 24 de Dezembro de 2013" "Version 2" "Controle de Acesso" \" -*- nroff -*-
.ad l
.nh
.SH NAME
model_mysql.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Componentes"

.in +1c
.ti -1c
.RI "class \fBmodel_mysql\&.Connect_Db\fP"
.br
.RI "\fIClasse de conexão e acesso ao banco de dados\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmodel_mysql\fP"
.br
.RI "\fIPacote com todas as funções de acesso ao banco de dados\&. \fP"
.in -1c
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Controle de Acesso a partir do código fonte\&.
