.TH "model_mysql.Connect_MySQL" 3 "Domingo, 15 de Dezembro de 2013" "Version 2" "Controle de Acesso" \" -*- nroff -*-
.ad l
.nh
.SH NAME
model_mysql.Connect_MySQL \- 
.PP
Classe de conexão e acesso ao banco de dados\&.  

.SH SYNOPSIS
.br
.PP
.SS "Membros públicos"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIInicializa o banco de dados\&. \fP"
.ti -1c
.RI "def \fBconecta\fP"
.br
.ti -1c
.RI "def \fBdropar_Tabelas\fP"
.br
.RI "\fIDeleta todas as tabelas se existirem\&. \fP"
.in -1c
.SS "Atributos Públicos"

.in +1c
.ti -1c
.RI "\fBhost\fP"
.br
.ti -1c
.RI "\fBuser\fP"
.br
.ti -1c
.RI "\fBpasswd\fP"
.br
.ti -1c
.RI "\fBconn\fP"
.br
.ti -1c
.RI "\fBcurs\fP"
.br
.in -1c
.SH "Descrição detalhada"
.PP 
Classe de conexão e acesso ao banco de dados\&. 
.PP
Definido na linha 8 do ficheiro model_mysql\&.py\&.
.SH "Documentação dos Construtores & Destrutor"
.PP 
.SS "def \fBmodel_mysql\&.Connect_MySQL\&.__init__\fP (self, host, user, passwd)"
.PP
Inicializa o banco de dados\&. \fBParâmetros:\fP
.RS 4
\fIhost\fP Servidor do banco de dados 
.br
\fIuser\fP Usuario do banco de dados 
.br
\fIpasswd\fP Senha do banco de dados 
.RE
.PP

.PP
Definido na linha 13 do ficheiro model_mysql\&.py\&.
.PP
.nf
13 
14     def __init__(self,host,user,passwd):
15 
16         self\&.host=host
17         self\&.user=user
18         self\&.passwd=passwd
19         self\&.conecta()
    
.fi
.SH "Documentação dos métodos"
.PP 
.SS "def \fBmodel_mysql\&.Connect_MySQL\&.conecta\fP (self)"
.PP
Definido na linha 20 do ficheiro model_mysql\&.py\&.
.PP
.nf
20 
21     def conecta(self):
22         try:
23             self\&.conn\&.close()
24         except Exception:
25             pass
26         self\&.conn = Connect(self\&.host, self\&.user, self\&.passwd,charset='utf8',use_unicode=True)
27         self\&.curs = self\&.conn\&.cursor()
28         self\&.curs\&.execute('USE controledeacesso')

.fi
.SS "def \fBmodel_mysql\&.Connect_MySQL\&.dropar_Tabelas\fP (self)"
.PP
Deleta todas as tabelas se existirem\&. 
.PP
Definido na linha 30 do ficheiro model_mysql\&.py\&.
.PP
.nf
30 
31     def dropar_Tabelas(self):
32         self\&.curs\&.execute('DROP TABLE IF EXISTS funcionarios')
33         self\&.curs\&.execute('DROP TABLE IF EXISTS horarios')
34         self\&.curs\&.execute('DROP TABLE IF EXISTS pontos')
35         self\&.curs\&.execute('DROP TABLE IF EXISTS log_porta')
        self\&.curs\&.execute('DROP TABLE IF EXISTS configuracoes')
.fi
.SH "Documentação dos dados membro"
.PP 
.SS "\fBmodel_mysql\&.Connect_MySQL::conn\fP"
.PP
Definido na linha 20 do ficheiro model_mysql\&.py\&.
.SS "\fBmodel_mysql\&.Connect_MySQL::curs\fP"
.PP
Definido na linha 20 do ficheiro model_mysql\&.py\&.
.SS "\fBmodel_mysql\&.Connect_MySQL::host\fP"
.PP
Definido na linha 13 do ficheiro model_mysql\&.py\&.
.SS "\fBmodel_mysql\&.Connect_MySQL::passwd\fP"
.PP
Definido na linha 13 do ficheiro model_mysql\&.py\&.
.SS "\fBmodel_mysql\&.Connect_MySQL::user\fP"
.PP
Definido na linha 13 do ficheiro model_mysql\&.py\&.

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Controle de Acesso a partir do código fonte\&.
