.TH "view.Tolerancias_Window" 3 "Terça, 24 de Dezembro de 2013" "Version 2" "Controle de Acesso" \" -*- nroff -*-
.ad l
.nh
.SH NAME
view.Tolerancias_Window \- 
.PP
Janela para configurar as tolerancias\&.  

.SH SYNOPSIS
.br
.PP
.PP
Derivada de \fBcda_tolerancias\&.Ui_Tolerancias_Window\fP\&.
.SS "Membros públicos"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBcenter\fP"
.br
.ti -1c
.RI "def \fBobter_Tolerancias\fP"
.br
.ti -1c
.RI "def \fBaltera_Atraso_Minimo\fP"
.br
.RI "\fIAltera o atraso maximo para não ser maior que a tolerancia de entrada\&. \fP"
.ti -1c
.RI "def \fBobter_Dados\fP"
.br
.RI "\fIObtem os dados da janela\&. \fP"
.ti -1c
.RI "def \fBpushButton_Salvar_Clicked\fP"
.br
.RI "\fISalva as configurações\&. \fP"
.in -1c
.SS "Atributos Públicos"

.in +1c
.ti -1c
.RI "\fBdb\fP"
.br
.in -1c
.SH "Descrição detalhada"
.PP 
Janela para configurar as tolerancias\&. 
.PP
Definido na linha 954 do ficheiro view\&.py\&.
.SH "Documentação dos Construtores & Destrutor"
.PP 
.SS "def \fBview\&.Tolerancias_Window\&.__init__\fP (self, parent = \fCNone\fP, db_dados = \fCNone\fP)"
.PP
Definido na linha 956 do ficheiro view\&.py\&.
.PP
.nf
956 
957     def __init__(self,parent=None,db_dados=None):
958         super(Tolerancias_Window, self)\&.__init__(parent)
959         self\&.setupUi(self)
960         self\&.db=Connect_Db(db_dados)
961         self\&.center()
962         self\&._configure()
963         self\&._set_connections()
964         self\&.show()

.fi
.SH "Documentação dos métodos"
.PP 
.SS "def \fBview\&.Tolerancias_Window\&.altera_Atraso_Minimo\fP (self)"
.PP
Altera o atraso maximo para não ser maior que a tolerancia de entrada\&. 
.PP
Definido na linha 996 do ficheiro view\&.py\&.
.PP
.nf
996 
997     def altera_Atraso_Minimo(self):
998         self\&.timeEdit_atraso\&.setMaximumTime(self\&.timeEdit_entrada_depois\&.time())

.fi
.SS "def \fBview\&.Tolerancias_Window\&.center\fP (self)"
.PP
Definido na linha 965 do ficheiro view\&.py\&.
.PP
.nf
965 
966     def center(self):
967         qr = self\&.frameGeometry()
968         cp = QDesktopWidget()\&.availableGeometry()\&.center()
969         qr\&.moveCenter(cp)
970         self\&.move(qr\&.topLeft())
    
.fi
.SS "def \fBview\&.Tolerancias_Window\&.obter_Dados\fP (self)"
.PP
Obtem os dados da janela\&. 
.PP
Definido na linha 1000 do ficheiro view\&.py\&.
.PP
.nf
1000 
1001     def obter_Dados(self):
1002         dados={}
1003         dados['entrada_antes']=str(self\&.timeEdit_entrada_antes\&.time()\&.toPython())
1004         dados['entrada_depois']=str(self\&.timeEdit_entrada_depois\&.time()\&.toPython())
1005         dados['saida_antes']=str(self\&.timeEdit_saida_antes\&.time()\&.toPython())
1006         dados['saida_depois']=str(self\&.timeEdit_saida_depois\&.time()\&.toPython())
1007         dados['atraso']=str(self\&.timeEdit_atraso\&.time()\&.toPython())
1008         return dados

.fi
.SS "def \fBview\&.Tolerancias_Window\&.obter_Tolerancias\fP (self)"
.PP
Definido na linha 980 do ficheiro view\&.py\&.
.PP
.nf
980 
981     def obter_Tolerancias(self):
982         self\&.db\&.obter_Configuracoes('tol_ent_ant')
983         dados={}
984         dados['entrada_antes']=self\&.db\&.obter_Configuracoes('tol_ent_ant')
985         dados['entrada_depois']=self\&.db\&.obter_Configuracoes('tol_ent_dep')
986         dados['saida_antes']=self\&.db\&.obter_Configuracoes('tol_sai_ant')
987         dados['saida_depois']=self\&.db\&.obter_Configuracoes('tol_sai_dep')
988         dados['atraso']=self\&.db\&.obter_Configuracoes('considerar_atraso')
989         return dados

.fi
.SS "def \fBview\&.Tolerancias_Window\&.pushButton_Salvar_Clicked\fP (self)"
.PP
Salva as configurações\&. 
.PP
Definido na linha 1010 do ficheiro view\&.py\&.
.PP
.nf
1010 
1011     def pushButton_Salvar_Clicked(self):
1012         dados=self\&.obter_Dados()
1013         self\&.db\&.atualizar_Configuracoes('tol_ent_ant',dados['entrada_antes'])
1014         self\&.db\&.atualizar_Configuracoes('tol_ent_dep',dados['entrada_depois'])
1015         self\&.db\&.atualizar_Configuracoes('tol_sai_ant',dados['saida_antes'])
1016         self\&.db\&.atualizar_Configuracoes('tol_sai_dep',dados['saida_depois'])
1017         self\&.db\&.atualizar_Configuracoes('considerar_atraso',dados['atraso'])
1018         msgBox = QMessageBox(self)
1019         msgBox\&.setText(u'As tolerancia foram alteradas')
1020         msgBox\&.exec_()
1021         self\&.close()
.fi
.SH "Documentação dos dados membro"
.PP 
.SS "\fBview\&.Tolerancias_Window::db\fP"
.PP
Definido na linha 956 do ficheiro view\&.py\&.

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Controle de Acesso a partir do código fonte\&.
