.TH "view.py" 3 "Terça, 24 de Dezembro de 2013" "Version 2" "Controle de Acesso" \" -*- nroff -*-
.ad l
.nh
.SH NAME
view.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Componentes"

.in +1c
.ti -1c
.RI "class \fBview\&.Controle_De_Acesso_Window\fP"
.br
.RI "\fIJanela principal do programa\&. \fP"
.ti -1c
.RI "class \fBview\&.Adm_Senha_Window\fP"
.br
.RI "\fIJanela para digitar senha de administrador\&. \fP"
.ti -1c
.RI "class \fBview\&.Altera_Senha_Window\fP"
.br
.RI "\fIJanela para alterar senha de administrador\&. \fP"
.ti -1c
.RI "class \fBview\&.Funcionarios_Window\fP"
.br
.RI "\fIJanela base para adicionar ou atualizar funcionarios\&. \fP"
.ti -1c
.RI "class \fBview\&.Add_Funcionarios_Window\fP"
.br
.RI "\fIJanela para adicionar funcionarios\&. \fP"
.ti -1c
.RI "class \fBview\&.Atualiza_Funcionarios_Window\fP"
.br
.RI "\fIJanela para atualizar funcionarios\&. \fP"
.ti -1c
.RI "class \fBview\&.Remover_Funcionarios_Window\fP"
.br
.RI "\fIJanela para remover funcionarios\&. \fP"
.ti -1c
.RI "class \fBview\&.Horarios_Window\fP"
.br
.RI "\fIJanela para visualizar os horarios dos funcionarios\&. \fP"
.ti -1c
.RI "class \fBview\&.Relatorios_Window\fP"
.br
.RI "\fIJanela para gerar os relatorios\&. \fP"
.ti -1c
.RI "class \fBview\&.Relatorios\fP"
.br
.RI "\fIThread para gerar os relatorios e não travar a interface grafica\&. \fP"
.ti -1c
.RI "class \fBview\&.Tolerancias_Window\fP"
.br
.RI "\fIJanela para configurar as tolerancias\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBview\fP"
.br
.RI "\fIImplementação dos eventos e configurações adicionais das interfaces graficas do programa\&. \fP"
.in -1c
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Controle de Acesso a partir do código fonte\&.
