.TH "view" 3 "Terça, 24 de Dezembro de 2013" "Version 2" "Controle de Acesso" \" -*- nroff -*-
.ad l
.nh
.SH NAME
view \- 
.PP
Implementação dos eventos e configurações adicionais das interfaces graficas do programa\&.  

.SH SYNOPSIS
.br
.PP
.SS "Componentes"

.in +1c
.ti -1c
.RI "class \fBControle_De_Acesso_Window\fP"
.br
.RI "\fIJanela principal do programa\&. \fP"
.ti -1c
.RI "class \fBAdm_Senha_Window\fP"
.br
.RI "\fIJanela para digitar senha de administrador\&. \fP"
.ti -1c
.RI "class \fBAltera_Senha_Window\fP"
.br
.RI "\fIJanela para alterar senha de administrador\&. \fP"
.ti -1c
.RI "class \fBFuncionarios_Window\fP"
.br
.RI "\fIJanela base para adicionar ou atualizar funcionarios\&. \fP"
.ti -1c
.RI "class \fBAdd_Funcionarios_Window\fP"
.br
.RI "\fIJanela para adicionar funcionarios\&. \fP"
.ti -1c
.RI "class \fBAtualiza_Funcionarios_Window\fP"
.br
.RI "\fIJanela para atualizar funcionarios\&. \fP"
.ti -1c
.RI "class \fBRemover_Funcionarios_Window\fP"
.br
.RI "\fIJanela para remover funcionarios\&. \fP"
.ti -1c
.RI "class \fBHorarios_Window\fP"
.br
.RI "\fIJanela para visualizar os horarios dos funcionarios\&. \fP"
.ti -1c
.RI "class \fBRelatorios_Window\fP"
.br
.RI "\fIJanela para gerar os relatorios\&. \fP"
.ti -1c
.RI "class \fBRelatorios\fP"
.br
.RI "\fIThread para gerar os relatorios e não travar a interface grafica\&. \fP"
.ti -1c
.RI "class \fBTolerancias_Window\fP"
.br
.RI "\fIJanela para configurar as tolerancias\&. \fP"
.in -1c
.SH "Descrição detalhada"
.PP 
Implementação dos eventos e configurações adicionais das interfaces graficas do programa\&. 
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Controle de Acesso a partir do código fonte\&.
