.TH "view.Horarios_Window" 3 "Terça, 24 de Dezembro de 2013" "Version 2" "Controle de Acesso" \" -*- nroff -*-
.ad l
.nh
.SH NAME
view.Horarios_Window \- 
.PP
Janela para visualizar os horarios dos funcionarios\&.  

.SH SYNOPSIS
.br
.PP
.PP
Derivada de \fBcda_horarios\&.Ui_Horarios_Window\fP\&.
.SS "Membros públicos"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBcenter\fP"
.br
.ti -1c
.RI "def \fBadiciona_TableView_Horarios\fP"
.br
.RI "\fIAdiciona um horario na lista de horarios  dia_da_semana Dia da semana considerando domingo=0, segunda=1 etc\&. \fP"
.ti -1c
.RI "def \fBmostra_Todos\fP"
.br
.RI "\fIMostra todos os funcionarios\&. \fP"
.in -1c
.SS "Atributos Públicos"

.in +1c
.ti -1c
.RI "\fBdb\fP"
.br
.ti -1c
.RI "\fBmodel_horarios\fP"
.br
.ti -1c
.RI "\fBlista_horarios\fP"
.br
.in -1c
.SH "Descrição detalhada"
.PP 
Janela para visualizar os horarios dos funcionarios\&. 
.PP
Definido na linha 783 do ficheiro view\&.py\&.
.SH "Documentação dos Construtores & Destrutor"
.PP 
.SS "def \fBview\&.Horarios_Window\&.__init__\fP (self, parent = \fCNone\fP, db_dados = \fCNone\fP)"
.PP
Definido na linha 785 do ficheiro view\&.py\&.
.PP
.nf
785 
786     def __init__(self,parent=None,db_dados=None):
787         super(Horarios_Window, self)\&.__init__(parent)
788         self\&.setupUi(self)
789         self\&.db=Connect_Db(db_dados)
790         self\&.center()
791         self\&._configure()
792         self\&.show()
793         self\&.mostra_Todos()

.fi
.SH "Documentação dos métodos"
.PP 
.SS "def \fBview\&.Horarios_Window\&.adiciona_TableView_Horarios\fP (self, nome, dia_da_semana, horario_inicial, horario_final)"
.PP
Adiciona um horario na lista de horarios  dia_da_semana Dia da semana considerando domingo=0, segunda=1 etc\&. \fBParâmetros:\fP
.RS 4
\fIhorario_inicial\fP Horario inicial no formato hh:mm:ss 
.br
\fIhorario_final\fP Horario final no formato hh:mm:ss 
.br
\fIid_horario\fP Id para o horario não necessario atualmente 
.RE
.PP

.PP
Definido na linha 813 do ficheiro view\&.py\&.
.PP
.nf
813 
814     def adiciona_TableView_Horarios(self,nome,dia_da_semana,horario_inicial,horario_final):
815         if not (isinstance(nome, str) or isinstance(nome, unicode)):
816             return False
817         if not isinstance(dia_da_semana, int):
818             return False
819         if not (isinstance(horario_inicial, str) or isinstance(horario_inicial, unicode)):
820             return False
821         if not (isinstance(horario_final, str) or isinstance(horario_final, unicode)):
822             return False
823         if not hasattr(self,'lista_horarios'):
824             self\&.lista_horarios=[]
825         nome_Item=QStandardItem(nome)
826         nome_Item\&.setEditable(False)
827         dia_da_semana_s=dia_Semana_Int2str(dia_da_semana)
828         dia_da_semana_s_Item=QStandardItem(dia_da_semana_s)
829         dia_da_semana_s_Item\&.setEditable(False)
830         horario_inicial_Item=QStandardItem(horario_inicial)
831         horario_inicial_Item\&.setEditable(False)
832         horario_final_Item=QStandardItem(horario_final)
833         horario_final_Item\&.setEditable(False)
834         self\&.model_horarios\&.appendRow ((nome_Item,dia_da_semana_s_Item,horario_inicial_Item,horario_final_Item))
835         return True

.fi
.SS "def \fBview\&.Horarios_Window\&.center\fP (self)"
.PP
Definido na linha 794 do ficheiro view\&.py\&.
.PP
.nf
794 
795     def center(self):
796         qr = self\&.frameGeometry()
797         cp = QDesktopWidget()\&.availableGeometry()\&.center()
798         qr\&.moveCenter(cp)
799         self\&.move(qr\&.topLeft())

.fi
.SS "def \fBview\&.Horarios_Window\&.mostra_Todos\fP (self)"
.PP
Mostra todos os funcionarios\&. 
.PP
Definido na linha 837 do ficheiro view\&.py\&.
.PP
.nf
837 
838     def mostra_Todos(self):
839         horarios=self\&.db\&.obter_Horarios()
840         for horario in horarios:
841             self\&.adiciona_TableView_Horarios(horario[0],int(horario[1]),str(horario[2]),str(horario[3]))

.fi
.SH "Documentação dos dados membro"
.PP 
.SS "\fBview\&.Horarios_Window::db\fP"
.PP
Definido na linha 785 do ficheiro view\&.py\&.
.SS "\fBview\&.Horarios_Window::lista_horarios\fP"
.PP
Definido na linha 813 do ficheiro view\&.py\&.
.SS "\fBview\&.Horarios_Window::model_horarios\fP"
.PP
Definido na linha 801 do ficheiro view\&.py\&.

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Controle de Acesso a partir do código fonte\&.
